-- Decision 112 — chargeback-pattern-restriction (Decision 68, Decision 111's own
-- deferred Phase B). Adds the two new columns Phase B's design needs:
-- Transaction.disputeLostAt (the persisted "resolved as lost" signal Decision
-- 68's own text requires and status=DISPUTED alone can't answer — see that
-- column's own schema.prisma comment) and User.paymentRestrictedAt (the
-- Cash/Bank-only purchase gate flag).
--
-- Additive-only (Decision 32) — no existing table/policy rewritten.
--
-- No new grant needed for Transaction (already whole-table `GRANT SELECT,
-- UPDATE ON "Transaction" TO ultm8_jobs`, 20260912000000_memberships_
-- transactions_module) or for ultm8_app on User (already whole-table CRUD,
-- 20260902000000_init) — both automatically cover a new column. ultm8_jobs's
-- own User grant is deliberately narrow and column-scoped
-- (20260918000000_notifications_module's own reasoning: User carries
-- passcodeHash and other PII no ultm8_jobs consumer has ever needed) —
-- extended below for exactly the one new column this job needs, and given a
-- new UPDATE policy since only a SELECT one existed for ultm8_jobs on User
-- before now.
--
-- Same provenance caveat as every prior migration in this repo: hand-authored,
-- not generated by `prisma migrate dev` (no reachable Postgres in this
-- environment at authoring time) — verify with a real Postgres run before
-- trusting this past a walking skeleton.

ALTER TABLE "Transaction" ADD COLUMN "disputeLostAt" TIMESTAMP(3);

ALTER TABLE "User" ADD COLUMN "paymentRestrictedAt" TIMESTAMP(3);

-- `updatedAt` is also granted here even though this job never sets it directly —
-- Prisma's own `@updatedAt` auto-touches it on every update() call, and Postgres
-- denies the WHOLE statement (a table-level "permission denied", not a
-- column-specific one) if ANY column referenced by an UPDATE lacks the grant, not
-- just the ones explicitly named in the query. FOUND ON REVIEW against a real
-- Postgres run — an earlier version of this migration granted only
-- "paymentRestrictedAt" and failed for exactly this reason.
GRANT SELECT ("paymentRestrictedAt"), UPDATE ("paymentRestrictedAt", "updatedAt") ON "User" TO ultm8_jobs;
CREATE POLICY "user_jobs_update" ON "User"
  FOR UPDATE
  TO ultm8_jobs
  USING (true)
  WITH CHECK (true);
