-- ULTM8 Phase 2 fix-forward — resolves Postgres 42P17 "infinite recursion detected in
-- policy for relation RoleGrant", caught by CI after 20260903000000_tenants_module_rls
-- shipped. Same provenance caveat as every migration before this one: hand-authored,
-- not generated by `prisma migrate dev` (no reachable Postgres in this environment) —
-- verify with a real `prisma migrate diff`/`migrate dev` run, same as always. Additive
-- fix-forward per the expand/contract convention (Decision 32) — the prior migration is
-- not edited; this one adds a function and ALTERs the one policy's expressions.
--
-- ROOT CAUSE (confirmed against CI's log, not re-diagnosed here): rolegrant_school_
-- manager_scope's USING/WITH CHECK clauses contained a plain, inline subquery against
-- "RoleGrant" — the same table the policy is ON. Postgres expands a policy's own
-- subqueries inline during query planning, including subqueries that reference the
-- table the policy protects; a self-referencing subquery like this has no base case
-- for that expansion to terminate on, so planning ANY query against RoleGrant failed
-- outright with 42P17 — not just queries that actually needed
-- rolegrant_school_manager_scope's branch of the OR. Worse, School/Branch/User's own
-- Phase 1 policies each subquery RoleGrant too (to check the caller's RoleGrant
-- membership), so evaluating THEIR policies now also required expanding RoleGrant's
-- (now-unresolvable) policy set — cascading the failure to essentially every
-- tenant-scoped query in the app, which is why Phase 1's own untouched RLS suite
-- (tenant-isolation.rls.spec.ts) started failing too, not just the new Phase 2 tests.
--
-- THE FIX: move the self-referencing membership check into a SECURITY DEFINER SQL
-- function and have the policy call it instead of inlining the subquery directly. This
-- is the standard, documented pattern for self-referential RLS checks (not specific to
-- this codebase) — it works because Postgres's planner never inlines a SECURITY
-- DEFINER function's body into the surrounding query (inlining would silently change
-- whose privileges the body runs with, so the planner deliberately excludes SECURITY
-- DEFINER functions from that optimization). The function call is therefore opaque at
-- *every* level of planning — evaluating the outer RoleGrant query, and evaluating the
-- function's own internal query, and (if it ever comes up) evaluating School/Branch/
-- User's subqueries into RoleGrant — none of them ever need to textually substitute
-- another copy of rolegrant_school_manager_scope's expression into themselves, so there
-- is no self-reference left for the planner to loop on.
--
-- THE PART THAT'S EASY TO GET WRONG (flagged explicitly, not assumed correct): SECURITY
-- DEFINER only fixes the COMPILE-TIME recursive-expansion error. It does NOT, by
-- itself, mean the function's own internal query skips RLS at RUN time — a SECURITY
-- DEFINER function executes with its OWNER's privileges, and RoleGrant has FORCE ROW
-- LEVEL SECURITY set, which explicitly removes the normal "table owner is exempt from
-- RLS" exemption. If this function were owned by an ordinary (non-superuser,
-- non-BYPASSRLS) role, its internal query would ITSELF be re-subject to RoleGrant's
-- full policy set (rolegrant_self_only OR rolegrant_school_manager_scope) at run time —
-- and rolegrant_school_manager_scope's branch would call this very function again.
-- Whether that actually terminates would then depend on Postgres choosing to
-- short-circuit the OR before evaluating the second (function-call) branch, which is
-- NOT a documented guarantee for policy quals — relying on it would just be trading one
-- unverified assumption (the one that caused this bug) for another. So: the function is
-- owned by a dedicated role with the BYPASSRLS attribute, created below specifically so
-- its internal query skips RLS on RoleGrant entirely, deterministically, regardless of
-- Postgres's evaluation order — not "probably fine because of short-circuiting."
--
-- REQUIRES: granting BYPASSRLS can only be done by a superuser (a hard Postgres rule,
-- not a project convention). CI's DATABASE_URL is the Docker Postgres image's default
-- `postgres` superuser (.github/workflows/ci.yml), so this migration applies cleanly
-- there. Confirm explicitly — do not assume — that whatever role runs
-- `prisma migrate deploy` in any other environment (local dev's `ultm8_owner`,
-- production) is ALSO a superuser before applying this migration there; if it isn't,
-- the CREATE ROLE ... BYPASSRLS statement below will fail with a permission error, not
-- silently do the wrong thing.

-- ============================================================================
-- 1. Dedicated, NOLOGIN, BYPASSRLS role — exists solely to own the function below.
--    Never connected to directly (NOLOGIN); its only purpose is to give the function a
--    SECURITY DEFINER identity that deterministically bypasses RLS on RoleGrant.
--    Idempotent creation, same pattern as ultm8_app/ultm8_auth in the init migration.
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ultm8_rls_helper') THEN
    CREATE ROLE ultm8_rls_helper NOLOGIN BYPASSRLS;
  END IF;
END
$$;

-- ============================================================================
-- 2. The membership-check function itself.
--    - STABLE, not VOLATILE: it only reads, and gives the planner room to avoid
--      re-evaluating it more than once per statement for the same arguments.
--    - SET search_path = '' + fully schema-qualified "public."RoleGrant"": standard
--      SECURITY DEFINER hardening — without a pinned search_path, a SECURITY DEFINER
--      function is a known privilege-escalation vector (a caller-controlled search_path
--      could point an unqualified table name at a different object the function owner
--      also has access to). Not a concern this schema currently creates a way to
--      exploit, but pinning it costs nothing and is the documented default-safe
--      practice for every SECURITY DEFINER function, not just this one.
--    - schoolId's SQL type is TEXT here (Prisma's `String @id @default(uuid())` maps to
--      TEXT, not native uuid, throughout this schema — see the init migration), not the
--      `uuid` type — matching the actual column type, not the illustrative sketch type.
-- ============================================================================

CREATE FUNCTION "is_active_school_owner_manager"(p_school_id text)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public."RoleGrant"
    WHERE "userId" = current_setting('app.current_user_id', true)
      AND "schoolId" = p_school_id
      AND "role" = 'SCHOOL_OWNER_MANAGER'
      AND "revokedAt" IS NULL
  );
$$;

ALTER FUNCTION "is_active_school_owner_manager"(text) OWNER TO ultm8_rls_helper;

-- Functions default to EXECUTE granted to PUBLIC, so ultm8_app could already call this
-- without this line — granted explicitly anyway so the privilege isn't left implicit,
-- matching this codebase's existing preference for explicit grants over relying on
-- Postgres defaults (see the init migration's GRANT statements).
GRANT EXECUTE ON FUNCTION "is_active_school_owner_manager"(text) TO ultm8_app;

-- ============================================================================
-- 3. Point the policy at the function instead of the inline self-referencing subquery.
--    Same policy name, same intent (a School Owner/Manager may see/write RoleGrant rows
--    scoped to a School they hold an active SCHOOL_OWNER_MANAGER grant on) — only the
--    expression changes, via ALTER POLICY rather than DROP/CREATE, so this stays a
--    minimal, in-place fix rather than restructuring the policy.
-- ============================================================================

ALTER POLICY "rolegrant_school_manager_scope" ON "RoleGrant"
  USING (
    "schoolId" IS NOT NULL
    AND is_active_school_owner_manager("schoolId")
  )
  WITH CHECK (
    "schoolId" IS NOT NULL
    AND is_active_school_owner_manager("schoolId")
  );
