-- ULTM8 Phase 47 — impersonation-scope RLS fix (Spec 55 §12.1 Decision 39,
-- "Platform Admin impersonation scope narrowed"). Closes the RLS-level gap Phase 46
-- (AuthService.issueImpersonationToken(), apps/api/src/auth/auth.service.ts)
-- deliberately did NOT attempt in the same pass: that phase scoped the
-- impersonation JWT's own `grants` claim to one School, but proved — by grep
-- (zero server-side consumers of payload.grants) and empirically over real HTTP
-- (GET /v1/schools returning both Schools for a School-A-scoped token) — that
-- RLS itself never consulted those claims. Every real access decision runs
-- through Postgres RLS keyed on app.current_user_id, which is the impersonated
-- user's REAL id, and RoleGrant's own policies read that user's REAL RoleGrant
-- rows with no awareness of which one School an impersonation session was
-- actually scoped to.
--
-- Same provenance caveat as every migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` — verify with a real Postgres run before
-- trusting this past a walking skeleton (done as part of this same phase; see
-- the full 28-suite / 278-test isolation-gate run in this PR's own description).
-- Additive-only in spirit (Decision 32) — no table is touched, only two
-- RoleGrant-owning policy/function definitions are narrowed, each provably a
-- no-op for every non-impersonated session (see each ALTER's own comment).

-- ============================================================================
-- THE MECHANISM: a second session variable, app.impersonation_school_id, set
-- alongside app.current_user_id (PrismaAppService.withTenantContext) whenever
-- the request is running under an active impersonation session (see the new
-- RequestContextService). Unset/empty for every ordinary (non-impersonated)
-- request — current_setting(..., true) returns NULL there, and every check
-- below short-circuits to its ORIGINAL, unmodified behavior in that case, so
-- normal sessions are provably unaffected by this migration.
--
-- WHY MODIFYING JUST TWO THINGS IS SUFFICIENT, not a piecemeal patch of the
-- ~20+ other tenant-scoped policies in this schema: every one of them (Class,
-- Booking, Membership, School, Franchise, ...) reaches RoleGrant only through a
-- PLAIN (non-SECURITY-DEFINER) inline subquery — and this codebase's own
-- established, twice-proven-the-hard-way rule
-- (20260904000000_fix_rolegrant_rls_recursion's own header comment) is that a
-- plain subquery into an RLS-protected table, executed by the non-BYPASSRLS
-- ultm8_app role, is ITSELF filtered by that table's own policies, even when
-- the subquery lives inside a DIFFERENT table's policy. So narrowing what
-- RoleGrant's OWN policies expose automatically narrows every downstream
-- policy's own EXISTS-against-RoleGrant subquery too, with no separate edit
-- needed per table.
--
-- The two things that must each be fixed directly, because each is either
-- RoleGrant's own base policy or independently bypasses RoleGrant's RLS on
-- purpose (full audit of every CREATE FUNCTION/CREATE POLICY/ALTER POLICY
-- across every prior migration — see this phase's own PR description for the
-- complete inventory):
--   1. rolegrant_self_only (20260902000000_init) — RoleGrant's own base
--      policy; every plain subquery elsewhere in the schema ultimately
--      depends on this.
--   2. is_active_school_owner_manager() (20260904000000) — a SECURITY
--      DEFINER BYPASSRLS function backing rolegrant_school_manager_scope,
--      deliberately reading RoleGrant UNFILTERED (that's the whole point of
--      the function — see that migration's own header comment) so it does
--      NOT inherit rolegrant_self_only's new restriction automatically and
--      needs the identical check added inside its own body.
--
-- THREE OTHER SECURITY DEFINER functions were audited and found NOT to need
-- this treatment, for two different reasons:
--   - school_has_any_role_grant() / franchise_has_any_role_grant()
--     (20260906000000, 20260920000000) are pure existence checks with no
--     caller-identity argument at all ("does ANY RoleGrant exist for this
--     School/Franchise, regardless of whose") — nothing to scope down, and
--     always false for a School/Franchise that's already real and owned,
--     which is the only case impersonation ever targets (the target user
--     must already hold an active grant there to be impersonated for it —
--     see AuthService.issueImpersonationToken()'s own 404 guard).
--   - school_exists() (20260919000000) checks School existence only, never
--     reads RoleGrant at all.
--
-- ONE MORE PATH, NOT AN RLS FIX — flagged here for a reader auditing this
-- migration, fixed at the application layer instead (FranchisesController,
-- not this file, not this migration): schools_for_franchise() (20260920000000)
-- is a purpose-built, BYPASSRLS endpoint function backing
-- GET /franchises/{id}/schools — deliberately NOT an RLS policy at all
-- (school_tenant_isolation's own Phase 1 comment: "Franchise Owner sees every
-- School under their Franchise" was deliberately kept OUT of RLS and built as
-- this separate, ownership-validated endpoint instead). Since it returns
-- every School under a Franchise with no way to further narrow the result to
-- "just the one School impersonation was scoped to" without changing its
-- whole contract, the controller now rejects this specific route outright for
-- an active impersonation session — the same "narrower than a real login, not
-- silently equivalent to one" posture Decision 102 already established for
-- writes generally.
-- ============================================================================

CREATE OR REPLACE FUNCTION "is_active_school_owner_manager"(p_school_id text)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public."RoleGrant"
    WHERE "userId" = current_setting('app.current_user_id', true)
      AND "schoolId" = p_school_id
      AND "role" = 'SCHOOL_OWNER_MANAGER'
      AND "revokedAt" IS NULL
  )
  AND (
    current_setting('app.impersonation_school_id', true) IS NULL
    OR current_setting('app.impersonation_school_id', true) = ''
    OR current_setting('app.impersonation_school_id', true) = p_school_id
  );
$$;

-- OWNER/GRANT unchanged from 20260904000000 — CREATE OR REPLACE preserves
-- neither automatically in every Postgres version, so both are re-asserted
-- explicitly rather than assumed carried over.
ALTER FUNCTION "is_active_school_owner_manager"(text) OWNER TO ultm8_rls_helper;
GRANT EXECUTE ON FUNCTION "is_active_school_owner_manager"(text) TO ultm8_app;

-- No WITH CHECK given here (none existed before this migration either) — Postgres
-- reuses a policy's USING expression for INSERT/UPDATE/DELETE when no separate
-- WITH CHECK is defined, exactly as it already did before this change; this
-- migration only narrows what USING itself evaluates to, for both reads and
-- writes alike, consistent with the policy's original single-expression shape.
-- Moot in practice for the impersonation case specifically — JwtStrategy already
-- rejects every non-GET/HEAD/OPTIONS request carrying an impersonation claim
-- before it ever reaches a controller, so no write ever reaches this policy
-- under an active impersonation session regardless.
ALTER POLICY "rolegrant_self_only" ON "RoleGrant"
  USING (
    "userId" = current_setting('app.current_user_id', true)
    AND (
      current_setting('app.impersonation_school_id', true) IS NULL
      OR current_setting('app.impersonation_school_id', true) = ''
      OR "schoolId" = current_setting('app.impersonation_school_id', true)
    )
  );
