-- ULTM8 Phase 12 — GuardianModule: Guardian linking + two-tier ConsentRecord
-- (Spec 55 §14). See the Phase 12 kickoff prompt for the full scoping rationale.
--
-- Additive-only (Decision 32) — no existing table/policy from any prior migration
-- is touched.
--
-- Same provenance caveat as every prior migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` (no reachable Postgres in this environment) —
-- verify with a real `prisma migrate diff`/`migrate dev` run before trusting this
-- past a walking skeleton.

CREATE TYPE "ConsentTier" AS ENUM ('BASELINE', 'CAMERA');
CREATE TYPE "ConsentStatus" AS ENUM ('ACTIVE', 'WITHDRAWN');

-- ============================================================================
-- GuardianLink — Guardian <-> linked minor Student. RLS: narrow, self-only, no
-- School scoping (this pairing has no School at all) and no shared-visibility
-- branch — only the Guardian who owns the link can see/write it. The linked
-- minor Student themselves gets no separate branch either (§14 doesn't confirm
-- the minor has independent visibility into who links them — see the kickoff
-- prompt §3 / Decision 92 for the full reasoning).
-- ============================================================================

-- FOUND ON REVIEW: an earlier version used ON DELETE CASCADE on both FKs below,
-- which contradicts this codebase's own established convention for exactly this
-- "no delete endpoint exists yet, but reason about it anyway" situation —
-- compare Booking.classId's own ON DELETE RESTRICT (Phase 11 migration, its own
-- comment: "cascading a hypothetical future Class deletion into deleting
-- Students' own booking history would be destructive"). ConsentRecord is
-- explicitly "a new, first-class, AUDITABLE, revocable consent entity"
-- (schema.prisma's own model comment) — CASCADE would let a future User
-- deletion (the exact action `account-deletion-processing`, referenced by name
-- in GuardiansService, is meant to eventually perform) silently destroy the very
-- WITHDRAWN ConsentRecord row that documents the cascade ran correctly, erasing
-- the audit evidence in the same stroke the deletion is supposed to be
-- evidenced by. RESTRICT instead, matching the Booking precedent.
CREATE TABLE "GuardianLink" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "guardianId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revokedAt" TIMESTAMP(3),
    CONSTRAINT "GuardianLink_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "GuardianLink_guardianId_fkey" FOREIGN KEY ("guardianId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "GuardianLink_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "GuardianLink_guardianId_studentId_key" ON "GuardianLink"("guardianId", "studentId");
CREATE INDEX "GuardianLink_studentId_idx" ON "GuardianLink"("studentId");

GRANT SELECT, INSERT, UPDATE, DELETE ON "GuardianLink" TO ultm8_app;

ALTER TABLE "GuardianLink" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GuardianLink" FORCE ROW LEVEL SECURITY;
CREATE POLICY "guardian_link_self_only" ON "GuardianLink"
  USING (
    "GuardianLink"."guardianId" = current_setting('app.current_user_id', true)
  );

-- ============================================================================
-- ConsentRecord — see schema.prisma's own model comment for the full RLS
-- reasoning (Decision 92): narrow self-only ALL-commands policy for the
-- Guardian who owns the record, PLUS a ultm8_jobs SELECT-only bypass so
-- Attendance (Phase 13) can check a specific Student's own camera-tier status
-- from an interactive scan request — the same class of gap Phase 11's own
-- review caught for Booking's capacity check, fixed here proactively rather
-- than rediscovered later.
-- ============================================================================

CREATE TABLE "ConsentRecord" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "guardianId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "tier" "ConsentTier" NOT NULL,
    "policyVersion" TEXT NOT NULL,
    "status" "ConsentStatus" NOT NULL DEFAULT 'ACTIVE',
    "consentedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "withdrawnAt" TIMESTAMP(3),
    CONSTRAINT "ConsentRecord_pkey" PRIMARY KEY ("id"),
    -- RESTRICT, not CASCADE — see GuardianLink's own comment above for the full
    -- audit-trail reasoning (same fix, same review finding, applies doubly here
    -- given this table's own explicit "auditable, revocable" purpose).
    CONSTRAINT "ConsentRecord_guardianId_fkey" FOREIGN KEY ("guardianId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "ConsentRecord_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "ConsentRecord_guardianId_studentId_tier_key" ON "ConsentRecord"("guardianId", "studentId", "tier");
CREATE INDEX "ConsentRecord_studentId_tier_idx" ON "ConsentRecord"("studentId", "tier");

GRANT SELECT, INSERT, UPDATE, DELETE ON "ConsentRecord" TO ultm8_app;

ALTER TABLE "ConsentRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ConsentRecord" FORCE ROW LEVEL SECURITY;
CREATE POLICY "consent_record_self_only" ON "ConsentRecord"
  USING (
    "ConsentRecord"."guardianId" = current_setting('app.current_user_id', true)
  );

-- ultm8_jobs: read-only, for Attendance's (Phase 13) interactive scan-time check
-- of a specific Student's own camera-tier consent status — NOT a background job
-- in the usual sense, but the same RLS-bypass mechanism/role already reused from
-- an interactive path for Booking's own occupancy count (Phase 11, Decision 89's
-- own addendum). No INSERT/UPDATE/DELETE — Guardians manage their own consent
-- exclusively through ultm8_app.
GRANT SELECT ON "ConsentRecord" TO ultm8_jobs;
CREATE POLICY "consent_record_jobs_read" ON "ConsentRecord"
  FOR SELECT
  TO ultm8_jobs
  USING (true);

-- ============================================================================
-- FOUND ON REVIEW, before this ever shipped: withdrawing BASELINE consent must
-- "cascade revoked_at onto every linked minor's own RoleGrant" (SKILL.md §14) —
-- but RoleGrant's own existing RLS (20260902000000_init's rolegrant_self_only:
-- "userId" = caller) means the GUARDIAN triggering the withdrawal can never
-- write to the MINOR's own RoleGrant rows under their own tenant context — the
-- exact same class of cross-user-write gap already found for Booking's capacity
-- check (Phase 11) and proactively closed above for ConsentRecord's own read.
-- ultm8_jobs did not previously have any grant on RoleGrant at all (grepped
-- every prior migration to confirm) — added here, SELECT+UPDATE only (the
-- cascade only ever revokes existing grants, never creates/deletes rows; INSERT/
-- DELETE stay exclusively interactive, under ultm8_app, via TenantsModule's own
-- existing RoleGrant-issuing endpoints).
-- ============================================================================
GRANT SELECT, UPDATE ON "RoleGrant" TO ultm8_jobs;
CREATE POLICY "role_grant_jobs_read" ON "RoleGrant"
  FOR SELECT
  TO ultm8_jobs
  USING (true);
CREATE POLICY "role_grant_jobs_update" ON "RoleGrant"
  FOR UPDATE
  TO ultm8_jobs
  USING (true)
  WITH CHECK (true);
