-- ULTM8 Phase 49 — TranslationsModule (ultm8-nestjs-module §5: i18n CMS,
-- Platform Admin authoring only — CRUD /translations, GET /translations?locale=&screen=).
-- Deferred from Phase 7 specifically because it needed Platform Admin's own identity
-- realm to exist first (see 20260910000000_settings_module/migration.sql's own header
-- comment) — that blocker resolved back at Phase 25 (PlatformAdminModule Slice 1).
--
-- Additive-only (Decision 32) — no existing table/policy from any prior migration is
-- touched.
--
-- Same provenance caveat as every prior migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` (no reachable Postgres in this environment at
-- authoring time) — verify with a real Postgres run before trusting this past a
-- walking skeleton.

CREATE TABLE "Translation" (
    "id" TEXT NOT NULL,
    "screen" TEXT NOT NULL,
    "labelKey" TEXT NOT NULL,
    "locale" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Translation_pkey" PRIMARY KEY ("id")
);

-- The natural key implied by the confirmed Translation shape (screen, labelKey,
-- locale, content — docs/ultm8-blueprint.html's own term glossary) — content is the
-- value, these three are the address. Enforced here, not just in TranslationsService,
-- so a raw client can't create a duplicate slot even if the app-layer check were ever
-- bypassed.
CREATE UNIQUE INDEX "Translation_screen_labelKey_locale_key" ON "Translation"("screen", "labelKey", "locale");

-- Baseline table privileges for ultm8_app — the role apps/api actually connects as
-- for every query (see PrismaAppService's header comment). Same convention every
-- prior migration in this repo grants on its own new table(s).
GRANT SELECT, INSERT, UPDATE, DELETE ON "Translation" TO ultm8_app;

-- Deliberately NO "ALTER TABLE ... ENABLE ROW LEVEL SECURITY" here — same precedent
-- LegalDocument's own migration (20260910000000_settings_module) and AdminUser's
-- (20260902000000_init) already established: global, platform-level content with no
-- tenant column has no per-caller row subset to restrict. See schema.prisma's own
-- Translation model comment for the full account, including why this table's id is a
-- Prisma-generated UUID rather than a human-meaningful key the way LegalDocument's
-- slug is — the real natural key here is the (screen, labelKey, locale) unique index
-- above, not the primary key.
