-- ULTM8 Phase 4 — ClassesModule (Class CRUD only; see the Phase 4 kickoff prompt for the
-- full scoping rationale — booking/waitlist and TimetableModule are both deliberately
-- out of scope here).
--
-- Additive-only (Decision 32) — no existing table/policy from 20260902000000/
-- 20260903000000/20260905000000/20260906000000 is touched.
--
-- Same provenance caveat as every prior migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` (no reachable Postgres in this environment) — verify
-- with a real `prisma migrate diff`/`migrate dev` run before trusting this past a walking
-- skeleton.

CREATE TABLE "Class" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "schoolId" TEXT NOT NULL,
    "branchId" TEXT,
    "instructorId" TEXT,
    "title" TEXT NOT NULL,
    "activities" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "bannerUrl" TEXT,
    "description" TEXT,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "capacity" INTEGER,
    "bookingEndAt" TIMESTAMP(3),
    "qrAttendanceEndAt" TIMESTAMP(3),
    "refundFeeDate" TIMESTAMP(3),
    "cancellationCharge" INTEGER,
    "termsWaiverRequired" BOOLEAN NOT NULL DEFAULT false,
    "membershipInclusion" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Class_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Class_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Class_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Class_instructorId_fkey" FOREIGN KEY ("instructorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
-- Composite indexes leading with the tenant column (Decision 30).
CREATE INDEX "Class_schoolId_idx" ON "Class"("schoolId");
CREATE INDEX "Class_schoolId_branchId_idx" ON "Class"("schoolId", "branchId");

-- ============================================================================
-- RLS — modeled directly on branch_tenant_isolation (20260902000000_init), which this
-- extends rather than copies verbatim: Class is the first RLS-protected table that is
-- itself a School-child table WITH ITS OWN nullable branchId column (Branch's own policy
-- only ever compares a grant's branchId against Branch.id — the row IS the branch).
--
-- Single USING-only policy (no separate WITH CHECK), same reasoning as Branch's own
-- policy: Postgres reuses USING for INSERT/UPDATE/DELETE when WITH CHECK is absent, and
-- that's safe here because a Class's schoolId (and branchId, when set) always reference
-- rows that already exist and that the caller already holds a RoleGrant against — there
-- is no bootstrap chicken-and-egg problem like School's own initial self-creation had
-- (20260903000000/20260906000000 fixed that one specifically for School; it doesn't
-- apply to a School-child row). This also depends on the only writer being School
-- Owner/Manager (enforced in ClassesService via TenantAuthorizationService, not here),
-- whose RoleGrant always has branchId NULL — so the "rg.branchId IS NULL" disjunct below
-- is always satisfied for every write that endpoint allows, regardless of what branchId
-- the Class row itself carries.
--
-- Read semantics (any active RoleGrant holder at the School, matching the existing
-- "School/Branch RLS admits any role, business-layer narrows writes" split):
--   - A School-level grant (branchId NULL — School Owner/Manager, or a School-scoped
--     Instructor) sees every Class at the School, any branch.
--   - A Branch-scoped grant (Branch Staff, or a Branch-scoped Instructor) sees Classes
--     explicitly scoped to their own Branch, PLUS School-wide Classes (branchId NULL) —
--     but never another Branch's Classes.
-- This three-way structure is genuinely new in this schema — flagged explicitly for
-- Architect review before this is trusted, same caution applied to every prior RLS
-- addition in this project (see 20260904000000/20260905000000/20260906000000's
-- fix-forward history for why that caution has already paid for itself once).

ALTER TABLE "Class" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Class" FORCE ROW LEVEL SECURITY;
CREATE POLICY "class_tenant_isolation" ON "Class"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "Class"."schoolId"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
        AND (
          rg."branchId" IS NULL
          OR "Class"."branchId" IS NULL
          OR rg."branchId" = "Class"."branchId"
        )
    )
  );
