-- ULTM8 Phase 10 — WaiversModule (Waiver assignment + Student e-signature only).
-- See the Phase 10 kickoff prompt for the full scoping rationale — Guardian-
-- signing (Decision 78) is out of scope: Guardian/ConsentRecord do not exist
-- anywhere in this codebase yet (verified directly, not assumed). Drawn-signature
-- capture (Decision 74's own engineering follow-up) is also out of scope — this
-- migration models the confirmed baseline mechanism (typed full name) only.
--
-- Additive-only (Decision 32) — no existing table/policy from any prior migration
-- is touched.
--
-- Same provenance caveat as every prior migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` (no reachable Postgres in this environment) —
-- verify with a real `prisma migrate diff`/`migrate dev` run before trusting this
-- past a walking skeleton.

CREATE TYPE "WaiverSignatureStatus" AS ENUM ('SIGNED', 'UNSIGNED', 'EXPIRED', 'PENDING');

-- ============================================================================
-- Waiver — a School's catalog of waiver documents. Public-visibility catalog
-- data, not a per-Student record — RLS shape matches Class/TimetableSlot/
-- MembershipPlan's own "any active RoleGrant holder at the School" pattern, NOT
-- WaiverSignature's narrower shape below (see that table's own header comment for
-- why those two need materially different policies — same split Phase 9 already
-- established between MembershipPlan and Membership/Transaction).
-- ============================================================================

CREATE TABLE "Waiver" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "schoolId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Waiver_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Waiver_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON "Waiver" TO ultm8_app;
CREATE INDEX "Waiver_schoolId_idx" ON "Waiver"("schoolId");

ALTER TABLE "Waiver" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Waiver" FORCE ROW LEVEL SECURITY;
CREATE POLICY "waiver_tenant_isolation" ON "Waiver"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "Waiver"."schoolId"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
  );

-- ============================================================================
-- WaiverSignature — one specific Student's own legal e-signature record. Same
-- narrow RLS shape Phase 9 established for Membership/Transaction (School Owner/
-- Manager full access; the row's own Student, self-only; no other role gets any
-- row access at all) — NOT Waiver's own broad catalog-read shape above. Spec 55
-- never states an explicit "no raw row access" rule for WaiverSignature the way
-- it does for Membership/Transaction (§8.2) — the absence of an explicit rule is
-- not confirmation that broad access is fine, so this picks the same safer
-- default Phase 9 already established for the identical class of concern (one
-- Student's own personal/legal record, not School-wide catalog data), flagged
-- for Architect confirmation rather than silently choosing the broader shape.
-- ============================================================================

CREATE TABLE "WaiverSignature" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "waiverId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "signerFullName" TEXT NOT NULL,
    "signatureText" TEXT NOT NULL,
    "signedDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" "WaiverSignatureStatus" NOT NULL DEFAULT 'SIGNED',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "WaiverSignature_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "WaiverSignature_waiverId_fkey" FOREIGN KEY ("waiverId") REFERENCES "Waiver"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "WaiverSignature_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "WaiverSignature_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON "WaiverSignature" TO ultm8_app;
CREATE INDEX "WaiverSignature_schoolId_idx" ON "WaiverSignature"("schoolId");
CREATE INDEX "WaiverSignature_studentId_idx" ON "WaiverSignature"("studentId");
CREATE INDEX "WaiverSignature_waiverId_idx" ON "WaiverSignature"("waiverId");

-- "Don't silently double-sign" — a Student may not hold two non-Expired
-- signatures for the same Waiver (Phase 10 kickoff prompt §2.2 — a Developer-
-- level inferred constraint, not a literal Spec 55 quote, flagged as such).
-- Partial unique index, not a plain @@unique — an Expired signature must not
-- block re-signing. Same atomic-constraint-over-app-layer-check philosophy Phase
-- 9 established for the two-simultaneous-Active-Membership rule.
CREATE UNIQUE INDEX "WaiverSignature_one_non_expired_per_student_per_waiver" ON "WaiverSignature"("waiverId", "studentId")
  WHERE "status" != 'EXPIRED';

ALTER TABLE "WaiverSignature" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WaiverSignature" FORCE ROW LEVEL SECURITY;
CREATE POLICY "waiver_signature_school_staff_or_self" ON "WaiverSignature"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "WaiverSignature"."schoolId"
        AND rg."role" = 'SCHOOL_OWNER_MANAGER'
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
    OR "WaiverSignature"."studentId" = current_setting('app.current_user_id', true)
  );
