/**
 * Shared payload shape for the `notification-fanout` queue — every producer
 * (WaiverSignatureRequestsProcessor today, more triggers in future phases)
 * and its one consumer (NotificationFanoutProcessor) import this instead of
 * each defining their own inline object shape, found on review to have
 * silently drifted from each other with no compiler check tying them
 * together.
 *
 * `notificationId` is REQUIRED, not generated by the consumer — every
 * producer must derive a stable, deterministic id from its own trigger
 * context (e.g. `waiver-${waiverId}-${userId}`), used as BOTH the BullMQ
 * `jobId` (queue-level dedup — re-enqueueing the same id while the original
 * job is still present/completed is a safe no-op) AND the Notification row's
 * own primary key (job-level retry safety — NotificationFanoutProcessor
 * upserts on this id, so a retried job attempt doesn't create a second row
 * for the same underlying event). See NotificationFanoutProcessor's own
 * header comment for the full reasoning.
 */
export interface NotificationFanoutJobData {
  notificationId: string;
  userId: string;
  title: string;
  body: string;
  type?: string;
}
