-- ULTM8 Phase 8 — PaymentsModule (PaymentAccount + Stripe Connect Express onboarding
-- + webhook-receiving infrastructure only; see the Phase 8 kickoff prompt for the full
-- scoping rationale — checkout, refunds, Cash/Bank confirmation, Franchise-fee
-- automation, and platform SubscriptionPlan/white-label billing are all deferred to
-- whenever Phase 9 (MembershipsModule) builds the entities they attach to:
-- MembershipPlan, Membership, Transaction, and Booking do not exist yet).
--
-- Stripe Connect account type is Express, not Standard — Decision 86
-- (docs/decisions/POST-SPEC-55-DECISION-LOG.md), resolving Spec 55 §12.2's own
-- "Still open — please advise" item directly with the product owner.
--
-- Additive-only (Decision 32) — no existing table/policy from any prior migration is
-- touched.
--
-- Same provenance caveat as every prior migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` (no reachable Postgres in this environment) —
-- verify with a real `prisma migrate diff`/`migrate dev` run before trusting this past
-- a walking skeleton. Given the sensitivity of this table, that verification matters
-- more here than for any prior phase.

-- Native Postgres enum types — matches this schema's own established convention
-- (20260902000000_init's CREATE TYPE "Role"/"FeeModel"/etc. AS ENUM), not a TEXT
-- column with a CHECK constraint (checked directly against the init migration before
-- writing this, not assumed).
CREATE TYPE "PaymentAccountProvider" AS ENUM ('STRIPE', 'CASH', 'BANK_TRANSFER');
CREATE TYPE "PaymentAccountStatus" AS ENUM ('ACTIVE', 'DE_ACTIVE');
CREATE TYPE "PaymentAccountMode" AS ENUM ('LIVE', 'TEST');

CREATE TABLE "PaymentAccount" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "schoolId" TEXT,
    "franchiseId" TEXT,
    "provider" "PaymentAccountProvider" NOT NULL,
    "accountTitle" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "status" "PaymentAccountStatus" NOT NULL DEFAULT 'ACTIVE',
    "mode" "PaymentAccountMode" NOT NULL DEFAULT 'TEST',
    "stripeConnectedAccountId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "PaymentAccount_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "PaymentAccount_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PaymentAccount_franchiseId_fkey" FOREIGN KEY ("franchiseId") REFERENCES "Franchise"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    -- "Belongs to School or Franchise, never both" — added on code review as a real
    -- DB-level CHECK, not application-code-only as schema.prisma's own comment
    -- originally left it ("no existing precedent in this schema for a multi-column
    -- exclusive-OR constraint"). Given how financially load-bearing this table is,
    -- defense-in-depth against a future write path that bypasses PaymentsService
    -- (a seed script, an admin tool, a rushed Phase 9 query) is worth the one line —
    -- unlike a lower-stakes table where app-only enforcement is an acceptable
    -- trade-off. A both-set or neither-set row would otherwise be visible/writable
    -- under either half of the RLS policy's OR clause below, straddling two tenants.
    CONSTRAINT "PaymentAccount_owner_xor_check" CHECK (num_nonnulls("schoolId", "franchiseId") = 1)
);

-- "One PaymentAccount per School, one per Franchise" — a nullable-column unique index
-- (Postgres treats NULL as distinct from NULL, so a Franchise-owned row's null
-- schoolId never collides with another Franchise-owned row's null schoolId) — same
-- established pattern Class's own @@unique([timetableSlotId, occurrenceDate]) already
-- relies on for its own nullable-pair uniqueness.
CREATE UNIQUE INDEX "PaymentAccount_schoolId_key" ON "PaymentAccount"("schoolId");
CREATE UNIQUE INDEX "PaymentAccount_franchiseId_key" ON "PaymentAccount"("franchiseId");
CREATE UNIQUE INDEX "PaymentAccount_stripeConnectedAccountId_key" ON "PaymentAccount"("stripeConnectedAccountId");

-- Baseline table privileges for ultm8_app — the role apps/api actually connects as
-- for every query (see PrismaAppService's header comment). Without this, every query
-- fails with Postgres 42501 ("permission denied for table PaymentAccount") before
-- anything else — the exact omission that cost Phase 4 a real CI failure on Class
-- (commit 2636873); Phases 5, 6, and 7 all got this right on the first attempt. Given
-- how sensitive this table is, get it right the first time here too, not as a
-- fix-forward.
GRANT SELECT, INSERT, UPDATE, DELETE ON "PaymentAccount" TO ultm8_app;

CREATE INDEX "PaymentAccount_schoolId_idx" ON "PaymentAccount"("schoolId");
CREATE INDEX "PaymentAccount_franchiseId_idx" ON "PaymentAccount"("franchiseId");

-- ============================================================================
-- RLS — PaymentAccount is a CHILD table of both School and Franchise (it carries its
-- own id, with schoolId/franchiseId as FK columns), not a second RLS root — modeled
-- directly on class_tenant_isolation's own "child compares against the FK column, not
-- the parent's own id" shape (20260907000000_classes_module), NOT on
-- school_tenant_isolation/franchise_tenant_isolation's own "root compares
-- RoleGrant.schoolId against School.id itself" shape (both checked directly against
-- 20260902000000_init before writing this, not assumed).
--
-- Single USING-only policy (no separate WITH CHECK), same reasoning every prior
-- School-child table in this schema already uses: the only writer is
-- School Owner/Manager or Franchise Owner (enforced in PaymentsService via
-- TenantAuthorizationService, not here), whose RoleGrant's schoolId/franchiseId
-- always exactly matches the row it's creating/updating.
--
-- Read semantics: a caller sees a PaymentAccount row if they hold ANY active
-- RoleGrant at the owning School (for a School-owned row) or the owning Franchise
-- (for a Franchise-owned row) — same "RLS admits any role, business layer narrows
-- writes" split this codebase has used since Phase 2.
-- ============================================================================

ALTER TABLE "PaymentAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentAccount" FORCE ROW LEVEL SECURITY;
CREATE POLICY "payment_account_tenant_isolation" ON "PaymentAccount"
  USING (
    ("schoolId" IS NOT NULL AND EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "PaymentAccount"."schoolId"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    ))
    OR
    ("franchiseId" IS NOT NULL AND EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."franchiseId" = "PaymentAccount"."franchiseId"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    ))
  );

-- ============================================================================
-- ProcessedStripeEvent — webhook idempotency ledger (Spec 55 §10.2's own confirmed
-- "dedupe on Stripe's event id" mechanism). No tenant column, no RLS — same
-- precedent AdminUser/LegalDocument already established for genuinely global,
-- platform-level tables.
--
-- Granted to ultm8_jobs, NOT ultm8_app — corrected on code review. An earlier draft
-- granted ultm8_app and had StripeWebhookProcessingProcessor query it via the bare
-- PrismaAppService client, citing SettingsService's LegalDocument lookup as
-- precedent. That precedent doesn't actually apply: SettingsService is an
-- HTTP-request-scoped, unauthenticated public route; StripeWebhookProcessingProcessor
-- is a background BullMQ worker with no single caller, the exact situation
-- ultm8_jobs/PrismaJobsService already exists for (see
-- 20260908000000_timetable_module's own header comment: "background jobs with no
-- single caller/tenant context to run withTenantContext(callerId, ...) under").
-- SELECT+INSERT only — no UPDATE/DELETE — matching ultm8_jobs's own established
-- narrow-grant convention (PrismaJobsService's own comment: "don't broaden a call
-- site here into a general-purpose cross-tenant read/write; add the specific grant a
-- new job actually needs").
-- ============================================================================

CREATE TABLE "ProcessedStripeEvent" (
    "stripeEventId" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "processedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ProcessedStripeEvent_pkey" PRIMARY KEY ("stripeEventId")
);

GRANT SELECT, INSERT ON "ProcessedStripeEvent" TO ultm8_jobs;
