-- Phase 54 — SubscriptionPlansModule (ultm8-nestjs-module §5: platform-level plans
-- a Franchise/School subscribes to, Platform Admin authoring only — GET /plans,
-- POST /plans/{id}/subscribe). Previously tracked as blocked on the
-- Franchise-Subscription-Plan billing-direction question; that citation was itself
-- stale (Decision 106, docs/decisions/POST-SPEC-55-DECISION-LOG.md) — this module
-- was simply never picked up, the same status TranslationsModule had before Phase 49.
--
-- Scope this phase (see the Phase 54 kickoff research pass for the full account):
-- SubscriptionPlan CRUD (Platform Admin authoring, no delete — see SubscriptionPlan's
-- own schema.prisma comment), Franchise/School subscribe/cancel against ULTM8's own
-- platform Stripe account (StripeClientService.platformClient(), never a tenant's
-- Connected Account), the PlatformCharge ledger, and a School-scoped read-only
-- degraded-portal gate (new Class/Booking/payment creation only) on Cancellation.
-- Deliberately deferred: the whiteLabelApp metered entitlement (rate unresolved,
-- Spec 55 §12.2, and gated on MobileAppPublishingModule anyway) and any
-- Franchise-side degraded-action gate (Spec 55 §10.2 names "profile/branding/
-- feeModel edits" specifically — no such endpoint gate is built this phase).
--
-- Additive-only (Decision 32) — no existing table/policy from any prior migration is
-- rewritten, only new grants/policies layered on top of Franchise/School exactly the
-- way 20260922000000_franchise_fee_charge_module already did for the sibling
-- franchise-fee billing relationship (mirrored throughout this file).
--
-- Same provenance caveat as every prior migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` (no reachable Postgres in this environment at
-- authoring time) — verify with a real Postgres run before trusting this past a
-- walking skeleton.

-- ============================================================================
-- 1. New enums.
-- ============================================================================

CREATE TYPE "PlatformSubscriptionStatus" AS ENUM ('ACTIVE', 'PAST_DUE', 'CANCELED');
CREATE TYPE "PlatformChargeType" AS ENUM ('SUBSCRIPTION_PLAN_FEE', 'WHITE_LABEL_APP_FEE');

-- ============================================================================
-- 2. SubscriptionPlan — new table. Global, Platform-Admin-authored content, no
--    tenant column — same "no RLS" shape Translation/LegalDocument already
--    established (see schema.prisma's own SubscriptionPlan comment for the full
--    account of why, and why both the public read and the admin CRUD hit this
--    same table through the plain ultm8_app role).
-- ============================================================================

CREATE TABLE "SubscriptionPlan" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "price" INTEGER NOT NULL,
    "featureList" TEXT[] NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "SubscriptionPlan_pkey" PRIMARY KEY ("id")
);

GRANT SELECT, INSERT, UPDATE ON "SubscriptionPlan" TO ultm8_app;
-- No DELETE grant — SubscriptionPlansService deliberately builds no delete path this
-- phase (see the model's own schema.prisma comment: deleting a Plan with active
-- Franchise/School subscribers has no confirmed, safe-orphaning behavior). Revisit
-- together with a real delete endpoint, not by granting the privilege ahead of it.

-- Deliberately NO "ALTER TABLE ... ENABLE ROW LEVEL SECURITY" — same precedent
-- Translation's own migration (20261003000000_translations_module) already
-- established for identical reasoning: global platform content with no tenant
-- column has no per-caller row subset to restrict.

-- ============================================================================
-- 3. Franchise / School — the platform SubscriptionPlan billing correlator trio,
--    mirroring the exact shape 20260922000000_franchise_fee_charge_module already
--    added for the sibling franchise-fee relationship (stripeFranchiseFeeSubscriptionId
--    + School.franchiseFeeSubscriptionStatus), applied here to BOTH Franchise and
--    School independently (Spec 55 §6.1: "Subscribed to by Franchise/School" — each
--    subscribes on its own, unlike franchise-fee billing which is School-only).
-- ============================================================================

ALTER TABLE "Franchise" ADD COLUMN "subscriptionPlanId" TEXT;
ALTER TABLE "Franchise" ADD COLUMN "stripePlatformSubscriptionId" TEXT;
ALTER TABLE "Franchise" ADD COLUMN "platformSubscriptionStatus" "PlatformSubscriptionStatus";
CREATE UNIQUE INDEX "Franchise_stripePlatformSubscriptionId_key" ON "Franchise"("stripePlatformSubscriptionId");
CREATE INDEX "Franchise_subscriptionPlanId_idx" ON "Franchise"("subscriptionPlanId");
ALTER TABLE "Franchise" ADD CONSTRAINT "Franchise_subscriptionPlanId_fkey" FOREIGN KEY ("subscriptionPlanId") REFERENCES "SubscriptionPlan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "School" ADD COLUMN "subscriptionPlanId" TEXT;
ALTER TABLE "School" ADD COLUMN "stripePlatformSubscriptionId" TEXT;
ALTER TABLE "School" ADD COLUMN "platformSubscriptionStatus" "PlatformSubscriptionStatus";
CREATE UNIQUE INDEX "School_stripePlatformSubscriptionId_key" ON "School"("stripePlatformSubscriptionId");
CREATE INDEX "School_subscriptionPlanId_idx" ON "School"("subscriptionPlanId");
ALTER TABLE "School" ADD CONSTRAINT "School_subscriptionPlanId_fkey" FOREIGN KEY ("subscriptionPlanId") REFERENCES "SubscriptionPlan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- No new RLS policy needed on either table — RLS is row-level, not column-level;
-- the existing school_tenant_isolation/franchise_tenant_isolation UPDATE policies
-- (already permitting a School Owner/Manager or Franchise Owner to update their own
-- row) already cover these new columns, the same "Branch's logoUrl/bannerUrl needed
-- no RLS changes either" precedent Phase 53 already established for this exact class
-- of change.

-- ultm8_jobs needs to flip platformSubscriptionStatus from stripe-webhook-processing's
-- new handlers (customer.subscription.deleted / invoice.paid / invoice.payment_failed
-- — see that file's own updated comments). School already holds an unrestricted
-- `GRANT UPDATE ON "School" TO ultm8_jobs` (20260922000000_franchise_fee_charge_module)
-- and an all-rows `school_jobs_update` policy — no new grant/policy needed there.
-- Franchise's own existing ultm8_jobs UPDATE grant is narrowly column-scoped
-- (stripeMeterId, stripeUsagePriceId only — see that migration's own "column-scope
-- the grant" reasoning) and its `franchise_jobs_update` policy is already row-
-- unrestricted (`USING(true) WITH CHECK(true)`), so only a NEW column needs adding to
-- the existing grant, not a new policy.
GRANT UPDATE ("platformSubscriptionStatus") ON "Franchise" TO ultm8_jobs;

-- ============================================================================
-- 4. PlatformCharge — new table. See schema.prisma's own model comment for the
--    full field-by-field account; mirrors FranchiseFeeCharge's shape but bills the
--    opposite direction (ULTM8 is the payee, not a tenant's own PaymentAccount) —
--    no `xPaymentAccountId` FK exists on this table for that reason.
-- ============================================================================

CREATE TABLE "PlatformCharge" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "schoolId" TEXT,
    "franchiseId" TEXT,
    "chargeType" "PlatformChargeType" NOT NULL,
    "amount" INTEGER NOT NULL,
    "currency" TEXT,
    "status" "TransactionStatus" NOT NULL,
    "stripeInvoiceId" TEXT,
    "stripeSubscriptionId" TEXT,
    "refundedAmount" INTEGER,
    "disputedAmount" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "PlatformCharge_pkey" PRIMARY KEY ("id"),
    -- RESTRICT, not CASCADE — same audit-trail-preservation precedent every other
    -- financial ledger table in this schema follows (Transaction, FranchiseFeeCharge).
    CONSTRAINT "PlatformCharge_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PlatformCharge_franchiseId_fkey" FOREIGN KEY ("franchiseId") REFERENCES "Franchise"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    -- "Belongs to whichever School or Franchise the platform-level charge is
    -- against" (Spec 55 §6.1) — exactly one of the two, never both, never neither.
    -- Prisma's schema DSL has no cross-field CHECK support (the same established
    -- limitation every partial-unique-index comment in this schema already notes
    -- for a different constraint shape); this exists only here, not in schema.prisma.
    CONSTRAINT "PlatformCharge_exactly_one_tenant_side" CHECK (
      ("schoolId" IS NOT NULL AND "franchiseId" IS NULL) OR
      ("schoolId" IS NULL AND "franchiseId" IS NOT NULL)
    )
);

CREATE UNIQUE INDEX "PlatformCharge_stripeInvoiceId_key" ON "PlatformCharge"("stripeInvoiceId");
CREATE INDEX "PlatformCharge_schoolId_idx" ON "PlatformCharge"("schoolId");
CREATE INDEX "PlatformCharge_franchiseId_idx" ON "PlatformCharge"("franchiseId");
CREATE INDEX "PlatformCharge_stripeSubscriptionId_status_idx" ON "PlatformCharge"("stripeSubscriptionId", "status");

-- No ultm8_app grant at all — deliberately internal-only this phase, no tenant-facing
-- read endpoint exists yet (see the model's own schema.prisma comment for why).
GRANT SELECT, INSERT, UPDATE ON "PlatformCharge" TO ultm8_jobs;

ALTER TABLE "PlatformCharge" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlatformCharge" FORCE ROW LEVEL SECURITY;

-- Jobs-only, unrestricted — mirrors franchise_fee_charge_jobs_all's identical shape.
-- No ultm8_app-facing policy exists at all (there is no grant for it to apply to
-- yet) — add one together with a real read endpoint + ultm8_app grant, not before.
CREATE POLICY "platform_charge_jobs_all" ON "PlatformCharge"
  TO ultm8_jobs
  USING (true)
  WITH CHECK (true);
