-- ULTM8 Phase 1 — initial migration.
--
-- IMPORTANT PROVENANCE NOTE: this file was hand-authored, not generated by
-- `prisma migrate dev`, because no Postgres instance was reachable in the
-- environment this was built in (checked: no local psql/docker). It is written to
-- match prisma/schema.prisma exactly, but it has NOT been verified by an actual
-- `prisma migrate diff`/`migrate dev` run against a real database. Before this is
-- trusted as the source of truth, run, in an environment with Postgres available:
--   npx prisma migrate dev --name init   (against an empty database, then diff
--   the result against this file and replace this file with the generated one).
--
-- Sources: see the header comment in schema.prisma for field-list citations.
-- RLS design below (session-variable convention, FORCE ROW LEVEL SECURITY, the
-- separate ultm8_app role) is a Developer-level implementation of the confirmed
-- principles in ultm8-tenant-isolation §2 ("RLS keys tenant tables on
-- franchise_id/school_id"; "a query missing a tenant filter returns nothing"; "School
-- Owner/Manager sees all Branches under this School") — it is NOT itself a spec
-- citation, since the spec never gets this concrete about session-variable mechanics.
-- Flagged for Architect review before this ships past a walking skeleton.

-- ============================================================================
-- Enums
-- ============================================================================

CREATE TYPE "Role" AS ENUM ('STUDENT', 'SCHOOL_OWNER_MANAGER', 'BRANCH_STAFF', 'INSTRUCTOR', 'FRANCHISE_OWNER', 'GUARDIAN');
CREATE TYPE "AdminSubRole" AS ENUM ('SUPPORT', 'BILLING_PAYMENTS_OPS', 'FULL_ADMIN');
CREATE TYPE "FeeModel" AS ENUM ('FLAT', 'PER_HEADCOUNT');
CREATE TYPE "ClassCancellationPolicy" AS ENUM ('MANUAL', 'AUTO_REFUND', 'AUTO_CREDIT');
CREATE TYPE "FranchiseFeeSubscriptionStatus" AS ENUM ('ACTIVE', 'PAST_DUE', 'CANCELED');

-- ============================================================================
-- Tables
-- ============================================================================

CREATE TABLE "User" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "email" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "surname" TEXT NOT NULL,
    "username" TEXT,
    "passcodeHash" TEXT NOT NULL,
    "phoneVerifiedAt" TIMESTAMP(3),
    "dateOfBirth" DATE NOT NULL,
    "gender" TEXT,
    "nationality" TEXT,
    "language" TEXT,
    "currency" TEXT,
    "address" TEXT,
    "profilePhotoUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "User_phone_key" ON "User"("phone");
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");
CREATE INDEX "User_email_idx" ON "User"("email");
CREATE INDEX "User_phone_idx" ON "User"("phone");

CREATE TABLE "AdminUser" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "subRole" "AdminSubRole" NOT NULL,
    "ssoSubject" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "revokedAt" TIMESTAMP(3),
    CONSTRAINT "AdminUser_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "AdminUser_email_key" ON "AdminUser"("email");
CREATE UNIQUE INDEX "AdminUser_ssoSubject_key" ON "AdminUser"("ssoSubject");
-- Deliberately no foreign key of any kind to "User" — AdminUser is a wholly separate
-- identity realm (ultm8-tenant-isolation §3). Do not add one later without an explicit
-- decision reversing that.

CREATE TABLE "Franchise" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "name" TEXT NOT NULL,
    "mobileNumber" TEXT,
    "address" TEXT,
    "type" TEXT,
    "activities" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "facilities" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "defaultLanguage" TEXT,
    "defaultCurrency" TEXT,
    "description" TEXT,
    "logoUrl" TEXT,
    "bannerUrl" TEXT,
    "feeModel" "FeeModel" NOT NULL DEFAULT 'FLAT',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Franchise_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Franchise_name_idx" ON "Franchise"("name");

CREATE TABLE "School" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "franchiseId" TEXT,
    "name" TEXT NOT NULL,
    "mobileNumber" TEXT,
    "address" TEXT,
    "businessType" TEXT,
    "activities" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "facilities" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "ranksToggle" BOOLEAN NOT NULL DEFAULT false,
    "defaultLanguage" TEXT,
    "defaultCurrency" TEXT,
    "description" TEXT,
    "logoUrl" TEXT,
    "bannerUrl" TEXT,
    "classCancellationPolicy" "ClassCancellationPolicy" NOT NULL DEFAULT 'MANUAL',
    "waitlistClaimWindowMinutes" INTEGER NOT NULL DEFAULT 120,
    "franchiseFeeSubscriptionStatus" "FranchiseFeeSubscriptionStatus",
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "School_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "School_franchiseId_fkey" FOREIGN KEY ("franchiseId") REFERENCES "Franchise"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "School_franchiseId_idx" ON "School"("franchiseId");

CREATE TABLE "Branch" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "schoolId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT,
    "contactPhone" TEXT,
    "timezone" TEXT,
    "currencyOverride" TEXT,
    "logoUrl" TEXT,
    "bannerUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Branch_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Branch_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "Branch_schoolId_idx" ON "Branch"("schoolId");

CREATE TABLE "RoleGrant" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "role" "Role" NOT NULL,
    "userId" TEXT NOT NULL,
    "franchiseId" TEXT,
    "schoolId" TEXT,
    "branchId" TEXT,
    "grantedById" TEXT,
    "grantedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revokedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "RoleGrant_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "RoleGrant_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "RoleGrant_franchiseId_fkey" FOREIGN KEY ("franchiseId") REFERENCES "Franchise"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "RoleGrant_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "RoleGrant_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "RoleGrant_grantedById_fkey" FOREIGN KEY ("grantedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
-- Composite indexes leading with the tenant column (Decision 30).
CREATE INDEX "RoleGrant_schoolId_revokedAt_idx" ON "RoleGrant"("schoolId", "revokedAt");
CREATE INDEX "RoleGrant_franchiseId_revokedAt_idx" ON "RoleGrant"("franchiseId", "revokedAt");
CREATE INDEX "RoleGrant_branchId_revokedAt_idx" ON "RoleGrant"("branchId", "revokedAt");
CREATE INDEX "RoleGrant_userId_idx" ON "RoleGrant"("userId");

-- ============================================================================
-- Application roles
--
-- Created BEFORE any RLS policy below, deliberately — the user_auth_lookup policy
-- further down grants privileges TO ultm8_auth specifically, and Postgres runs a
-- migration's statements sequentially, so that role must already exist by the time
-- that CREATE POLICY statement runs. (This is the fix for CI run failure P3018 /
-- "role ultm8_auth does not exist" — the roles used to be created in a block at the
-- end of this file, after the policy that references one of them.)
--
-- ultm8_app is the role apps/api actually connects as for tenant-scoped queries
-- (DATABASE_URL_APP in .env.example). It deliberately does NOT own these tables and is
-- NOT a superuser — both would silently bypass RLS regardless of FORCE, defeating the
-- point. Migrations themselves still run as the table-owning/superuser connection
-- (DATABASE_URL), which is standard and does not go through this role.
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ultm8_app') THEN
    CREATE ROLE ultm8_app LOGIN PASSWORD 'changeme';
  END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO ultm8_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "User", "AdminUser", "Franchise", "School", "Branch", "RoleGrant" TO ultm8_app;
-- AdminUser has no RLS policy (not tenant data, §4.4) — access to it is gated entirely
-- at the application layer via the separate Platform Admin identity realm, which
-- doesn't exist yet in this phase (PlatformAdminModule is out of scope).

-- ultm8_auth: minimal, SELECT-only role for the pre-authentication credential-lookup
-- path (see the user_auth_lookup policy below). Deliberately cannot INSERT/UPDATE/
-- DELETE anything, and has no grant on any table but User.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ultm8_auth') THEN
    CREATE ROLE ultm8_auth LOGIN PASSWORD 'changeme';
  END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO ultm8_auth;
GRANT SELECT ON "User" TO ultm8_auth;

-- ============================================================================
-- Row-Level Security
--
-- Convention: every tenant-scoped query runs inside a transaction that first sets
-- `app.current_user_id` (the authenticated User's uuid, as text) via SET LOCAL. See
-- apps/api/src/common/prisma/tenant-context.ts for the app-side half of this.
--
-- current_setting(..., true) returns NULL when unset, and comparing NULL always
-- evaluates false — so a request that never establishes a tenant context sees zero
-- rows, matching the confirmed "a query missing a tenant filter returns nothing"
-- principle, not an error that might get swallowed.
--
-- FORCE ROW LEVEL SECURITY is required on every table below — without it, Postgres
-- exempts the table owner from RLS entirely, which would silently defeat this the
-- moment the app's migration role is reused for queries. ultm8_app (created above) is
-- deliberately NOT the table owner and NOT a superuser, so policies apply to it.
-- ============================================================================

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" FORCE ROW LEVEL SECURITY;
-- A User is visible to themself, or to anyone who shares an active School-scoped
-- RoleGrant with them (the "School staff can see other School staff/Instructors/
-- Students affiliated with the same School" case). This is a Developer-level reading
-- of the confirmed "no cross-tenant visibility" principle — User has no franchise_id/
-- school_id column of its own, so the policy joins through RoleGrant instead.
CREATE POLICY "user_self_or_shared_school" ON "User"
  USING (
    "id" = current_setting('app.current_user_id', true)
    OR EXISTS (
      SELECT 1 FROM "RoleGrant" mine
      JOIN "RoleGrant" theirs ON theirs."schoolId" = mine."schoolId"
      WHERE mine."userId" = current_setting('app.current_user_id', true)
        AND mine."revokedAt" IS NULL
        AND mine."schoolId" IS NOT NULL
        AND theirs."userId" = "User"."id"
        AND theirs."revokedAt" IS NULL
    )
  )
  WITH CHECK (
    -- Registration bootstrapping: the app generates the new User's id, sets
    -- app.current_user_id to that same id for the transaction, then inserts — so a
    -- brand-new row with no RoleGrant yet still satisfies this check. See
    -- AuthService.register().
    "id" = current_setting('app.current_user_id', true)
  );

-- Pre-authentication credential lookup (login-by-email, registration's
-- email/phone-already-taken check) inherently has no tenant/user context to set yet —
-- that's the whole point of the endpoint. A User's email/phone aren't themselves
-- tenant-scoped identifiers (a person's identity spans Schools, confirmed §6.1), so
-- this isn't a tenant-boundary crossing; it's a second, additive PERMISSIVE policy
-- (Postgres OR-combines permissive policies) scoped to a distinct, SELECT-only role
-- that only AuthService's credential-lookup path connects as. It is never granted
-- INSERT/UPDATE/DELETE, so the WITH CHECK above still governs every write.
CREATE POLICY "user_auth_lookup" ON "User"
  FOR SELECT
  TO ultm8_auth
  USING (true);

ALTER TABLE "RoleGrant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RoleGrant" FORCE ROW LEVEL SECURITY;
-- Phase 1 has no RoleGrant-issuing endpoint yet (TenantsModule is out of scope) — this
-- policy is intentionally conservative: a caller sees only their own grants. Widen this
-- deliberately, not by default, once TenantsModule ships and School Owner/Manager needs
-- to read grants across their own School.
CREATE POLICY "rolegrant_self_only" ON "RoleGrant"
  USING ("userId" = current_setting('app.current_user_id', true));

ALTER TABLE "Franchise" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Franchise" FORCE ROW LEVEL SECURITY;
CREATE POLICY "franchise_tenant_isolation" ON "Franchise"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."franchiseId" = "Franchise"."id"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
  );

ALTER TABLE "School" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "School" FORCE ROW LEVEL SECURITY;
-- Deliberately NOT extended to "Franchise Owner sees every School under their
-- Franchise" — that's confirmed to be a purpose-built, ownership-validated endpoint
-- (GET /franchises/{id}/schools), explicitly NOT an RLS escalation into School-scoped
-- tables (ultm8-tenant-isolation §5). Baking it into this policy instead would
-- contradict that.
CREATE POLICY "school_tenant_isolation" ON "School"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "School"."id"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
  );

ALTER TABLE "Branch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Branch" FORCE ROW LEVEL SECURITY;
-- A grant with schoolId set and branchId NULL sees every Branch under that School
-- ("School Owner/Manager sees all Branches under this School", confirmed §4.3); a
-- grant with branchId set is restricted to that one Branch (Branch Staff).
CREATE POLICY "branch_tenant_isolation" ON "Branch"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "Branch"."schoolId"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
        AND (rg."branchId" IS NULL OR rg."branchId" = "Branch"."id")
    )
  );

