-- ULTM8 Phase 5 — TimetableModule (TimetableSlot CRUD + class-occurrence-generation).
-- See the Phase 5 kickoff prompt for the full scoping rationale, including the
-- template-field design on TimetableSlot (resolved with the product owner during
-- scoping — record as a Decision after this ships, same as Decisions 82-84) and the
-- three items deliberately deferred (the job's platform-SubscriptionPlan skip
-- condition, LoginAttemptTracker's separate Redis gap, the job's exact cadence).
--
-- Additive-only (Decision 32) — no existing table/policy is touched, only ALTERed to
-- add a new nullable column pair to "Class".
--
-- Same provenance caveat as every prior migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` (no reachable Postgres in this environment) —
-- verify with a real `prisma migrate diff`/`migrate dev` run before trusting this past
-- a walking skeleton.
--
-- A REAL GAP THE KICKOFF PROMPT DIDN'T ADDRESS, FOUND DURING IMPLEMENTATION: every
-- existing Postgres role in this schema is either a single caller's RLS-scoped
-- connection (ultm8_app) or narrowly single-purpose (ultm8_auth, ultm8_rls_helper).
-- class-occurrence-generation is a genuine system-level sweep across EVERY School's
-- active TimetableSlots — it has no single caller/tenant context to run
-- withTenantContext(callerId, ...) under. Rather than invent a new pattern, this
-- follows the existing ultm8_auth precedent exactly: a dedicated, narrowly-scoped
-- LOGIN role (own connection string, own additive RLS policies granting it exactly
-- what it needs and nothing else — same "don't broaden a call site into a
-- general-purpose cross-tenant read" discipline PrismaAuthService's own header comment
-- states for ultm8_auth). Flagged for Architect review as a new architectural
-- decision, same as everything else inferred this phase.
--
-- ultm8_jobs gets: SELECT on TimetableSlot (find active slots) and Branch (read
-- timezone) — both via an additive permissive RLS policy, USING (true), TO
-- ultm8_jobs, OR-combined with the existing tenant-scoped policies on those tables
-- (same multi-policy pattern rolegrant_school_manager_scope already established) —
-- plus INSERT and SELECT (not UPDATE/DELETE) on Class: INSERT for materializing new
-- occurrences, and SELECT because Prisma's `.create()` always does
-- `INSERT ... RETURNING *`, which Postgres RLS requires a passing SELECT-context USING
-- policy for, not just WITH CHECK — the exact bug this project already hit and fixed
-- once for School's own self-service creation (commit 8bd7cd4), caught again here by
-- CI on this migration's first real run and fixed in place. UPDATE/DELETE deliberately
-- withheld — the job never modifies or deletes an already-materialized Class, and
-- relies on the Class_timetableSlotId_occurrenceDate_key unique constraint (added
-- below) to reject a duplicate on INSERT rather than needing a separate check-first
-- SELECT. Deliberately NOT granted anything on School directly — the platform-
-- SubscriptionPlan skip condition that would need it is deferred (see the kickoff
-- prompt), so there's nothing for this role to read there yet; add that grant when
-- that gap closes, not preemptively.

-- ultm8_jobs: dedicated LOGIN role for background jobs with no single caller/tenant
-- context (class-occurrence-generation, this migration; a future job could reuse it
-- the same way ultm8_auth serves more than one call site). Created before any policy
-- references it, same convention as ultm8_app/ultm8_auth in the init migration.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ultm8_jobs') THEN
    CREATE ROLE ultm8_jobs LOGIN PASSWORD 'changeme';
  END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO ultm8_jobs;

CREATE TYPE "Weekday" AS ENUM ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY');
CREATE TYPE "TimetableSlotStatus" AS ENUM ('ON', 'OFF');

CREATE TABLE "TimetableSlot" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "schoolId" TEXT NOT NULL,
    "branchId" TEXT,
    "instructorId" TEXT,
    "weekday" "Weekday" NOT NULL,
    "startTime" TIME(0) NOT NULL,
    "endTime" TIME(0) NOT NULL,
    "breakStart" TIME(0),
    "breakEnd" TIME(0),
    "status" "TimetableSlotStatus" NOT NULL DEFAULT 'ON',
    "title" TEXT NOT NULL,
    "activities" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "capacity" INTEGER,
    "description" TEXT,
    "bannerUrl" TEXT,
    "termsWaiverRequired" BOOLEAN NOT NULL DEFAULT false,
    "membershipInclusion" BOOLEAN NOT NULL DEFAULT false,
    "bookingCutoffMinutesBeforeStart" INTEGER,
    "qrAttendanceWindowMinutes" INTEGER,
    "refundCutoffHoursBeforeStart" INTEGER,
    "cancellationCharge" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "TimetableSlot_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "TimetableSlot_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "TimetableSlot_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "TimetableSlot_instructorId_fkey" FOREIGN KEY ("instructorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- Baseline table privileges for ultm8_app — get it right in the same migration this
-- time (Phase 4's equivalent migration shipped without this and CI caught it
-- immediately as Postgres 42501, "permission denied for table Class" — see
-- 20260907000000_classes_module's own header comment for the full story).
GRANT SELECT, INSERT, UPDATE, DELETE ON "TimetableSlot" TO ultm8_app;

-- Composite indexes leading with the tenant column (Decision 30).
CREATE INDEX "TimetableSlot_schoolId_idx" ON "TimetableSlot"("schoolId");
CREATE INDEX "TimetableSlot_schoolId_branchId_idx" ON "TimetableSlot"("schoolId", "branchId");

-- ============================================================================
-- RLS — identical shape to class_tenant_isolation (20260907000000_classes_module):
-- same three-way branch OR, same reasoning for why a single USING-only policy (no
-- separate WITH CHECK) is safe (School Owner/Manager is the only writer per
-- TimetableSlotsService, and their RoleGrant is always branchId NULL).
-- ============================================================================

ALTER TABLE "TimetableSlot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TimetableSlot" FORCE ROW LEVEL SECURITY;
CREATE POLICY "timetable_slot_tenant_isolation" ON "TimetableSlot"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "TimetableSlot"."schoolId"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
        AND (
          rg."branchId" IS NULL
          OR "TimetableSlot"."branchId" IS NULL
          OR rg."branchId" = "TimetableSlot"."branchId"
        )
    )
  );

-- Additive second permissive policy (Postgres OR-combines multiple permissive
-- policies for the same command, same pattern rolegrant_school_manager_scope already
-- established) — lets ultm8_jobs read every active TimetableSlot across every School,
-- deliberately unrestricted (USING (true)) since the job's whole point is a
-- cross-tenant sweep. Does not touch timetable_slot_tenant_isolation above; ultm8_app
-- stays exactly as scoped.
GRANT SELECT ON "TimetableSlot" TO ultm8_jobs;
CREATE POLICY "timetable_slot_jobs_read" ON "TimetableSlot"
  FOR SELECT
  TO ultm8_jobs
  USING (true);

-- Same additive-policy pattern for Branch — the job needs Branch.timezone to resolve
-- each occurrence's wall-clock time into the correct UTC instant.
GRANT SELECT ON "Branch" TO ultm8_jobs;
CREATE POLICY "branch_jobs_read" ON "Branch"
  FOR SELECT
  TO ultm8_jobs
  USING (true);

-- ============================================================================
-- Class gains a nullable link back to the TimetableSlot it was materialized from
-- (Spec 55 §6.1: "optionally generated from a recurring TimetableSlot (nullable
-- timetableSlotId)"), plus a date-only companion column that turns the
-- class-occurrence-generation job's "unless one already exists for that slot+date"
-- into a real DB-level guarantee (a unique constraint) rather than an
-- application-level check-then-insert race.
-- ============================================================================

ALTER TABLE "Class" ADD COLUMN "timetableSlotId" TEXT;
ALTER TABLE "Class" ADD COLUMN "occurrenceDate" DATE;
ALTER TABLE "Class" ADD CONSTRAINT "Class_timetableSlotId_fkey" FOREIGN KEY ("timetableSlotId") REFERENCES "TimetableSlot"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE INDEX "Class_timetableSlotId_idx" ON "Class"("timetableSlotId");
-- Postgres treats NULL as distinct from NULL in a unique constraint, so this imposes
-- no restriction on one-off Classes (timetableSlotId/occurrenceDate both null) — it
-- only ever blocks a second materialized Class for the same slot on the same date.
ALTER TABLE "Class" ADD CONSTRAINT "Class_timetableSlotId_occurrenceDate_key" UNIQUE ("timetableSlotId", "occurrenceDate");

-- CI CAUGHT A REAL BUG HERE (fixed in place — never shipped anywhere): the original
-- version of this migration granted ultm8_jobs INSERT-only on Class, reasoning "the job
-- never needs to read Class back". That's true in the abstract, but Prisma's `.create()`
-- always issues `INSERT ... RETURNING *` to get the full row (including server-generated
-- defaults like createdAt) back for the object it returns — and Postgres requires a
-- newly-inserted row to ALSO satisfy the table's SELECT-context USING policy for
-- RETURNING to hand it back, not just WITH CHECK. This is the exact same class of bug
-- already hit and fixed once in this project for School's own self-service creation
-- (see commit 8bd7cd4, "School INSERT RETURNING") — recognized immediately from CI's
-- error rather than re-diagnosed from scratch, though the two manifest slightly
-- differently: School's case failed as "new row violates row-level security policy"
-- (a real USING policy existed but evaluated false); ultm8_jobs has no SELECT
-- privilege on Class at all, so this failed one level earlier as plain
-- "permission denied for table Class" (42501).
GRANT INSERT, SELECT ON "Class" TO ultm8_jobs;
CREATE POLICY "class_jobs_insert" ON "Class"
  FOR INSERT
  TO ultm8_jobs
  WITH CHECK (true);
-- Required for RETURNING, not a genuine expansion of what this role does — it still
-- never issues an independent SELECT query against Class outside of what INSERT's own
-- RETURNING clause already exposes (the row it just wrote).
CREATE POLICY "class_jobs_select_for_returning" ON "Class"
  FOR SELECT
  TO ultm8_jobs
  USING (true);
