-- ULTM8 Phase 6 — InstructorsModule (Instructor profile CRUD only; see the Phase 6
-- kickoff prompt for the full scoping rationale — attendance-scan and booking-override
-- are both deliberately out of scope here, and UsersModule's GET/PATCH /users/me needs
-- no schema change at all, since User already exists from Phase 1).
--
-- Additive-only (Decision 32) — no existing table/policy from any prior migration is
-- touched.
--
-- Same provenance caveat as every prior migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` (no reachable Postgres in this environment) — verify
-- with a real `prisma migrate diff`/`migrate dev` run before trusting this past a walking
-- skeleton.
--
-- This table is NOT the FK target for Class.instructorId/TimetableSlot.instructorId —
-- those stay pointed at User directly, per the Phase 4/5 decision restated in both
-- schema.prisma's Class model comment and TenantAuthorizationService.assertValidInstructor's
-- docblock ("'taught by an Instructor' means instructorId references a User holding an
-- active INSTRUCTOR RoleGrant — not a separate Instructor table"). This table is a
-- separate concern: a profile/bio extension for a person who already holds that role,
-- checked against RoleGrant at write time (InstructorsService), never consulted to
-- answer "does this User hold the Instructor role" itself. See the Phase 6 kickoff
-- prompt and schema.prisma's own Instructor model comment for the full reasoning.

CREATE TABLE "Instructor" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "userId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "branchId" TEXT,
    "photoUrl" TEXT,
    "beltRanking" TEXT,
    "specializations" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "phone" TEXT,
    "yearsOfExperience" INTEGER,
    "bio" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Instructor_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Instructor_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Instructor_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Instructor_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- One profile per person per School — deliberately NOT also keyed on branchId. See
-- schema.prisma's Instructor model comment for why (an Instructor's RoleGrant can be
-- Branch-scoped at more than one Branch of the same School; this design still gives
-- them one shared profile row, flagged for Architect review as an inferred
-- simplification).
CREATE UNIQUE INDEX "Instructor_schoolId_userId_key" ON "Instructor"("schoolId", "userId");

-- Baseline table privileges for ultm8_app — get it right in the same migration from
-- the start (Phase 4's equivalent migration shipped without this and CI caught it
-- immediately as Postgres 42501, "permission denied for table Class" — see
-- 20260907000000_classes_module's own header comment for the full story; Phase 5's
-- TimetableSlot migration already got it right first try, so this is the second
-- migration in a row not to repeat that mistake, not the third).
GRANT SELECT, INSERT, UPDATE, DELETE ON "Instructor" TO ultm8_app;

-- Composite indexes leading with the tenant column (Decision 30).
CREATE INDEX "Instructor_schoolId_idx" ON "Instructor"("schoolId");
CREATE INDEX "Instructor_schoolId_branchId_idx" ON "Instructor"("schoolId", "branchId");
CREATE INDEX "Instructor_userId_idx" ON "Instructor"("userId");

-- ============================================================================
-- RLS — identical shape to class_tenant_isolation (20260907000000_classes_module) and
-- timetable_slot_tenant_isolation (20260908000000_timetable_module): same three-way
-- branch OR, same reasoning for why a single USING-only policy (no separate WITH
-- CHECK) is safe here (School Owner/Manager is the only writer, per InstructorsService,
-- and their RoleGrant is always branchId NULL, so the "rg.branchId IS NULL" disjunct is
-- always satisfied for every write that endpoint allows).
--
-- Read semantics (any active RoleGrant holder at the School — same "RLS admits any
-- role, business-layer narrows writes" split as Class/TimetableSlot):
--   - A School-level grant (branchId NULL) sees every Instructor profile at the
--     School, any branch.
--   - A Branch-scoped grant sees profiles explicitly scoped to their own Branch, PLUS
--     School-wide profiles (branchId NULL) — but never another Branch's profiles.
-- Flagged for Architect review same as the other two branch-aware tables.
-- ============================================================================

ALTER TABLE "Instructor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Instructor" FORCE ROW LEVEL SECURITY;
CREATE POLICY "instructor_tenant_isolation" ON "Instructor"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "Instructor"."schoolId"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
        AND (
          rg."branchId" IS NULL
          OR "Instructor"."branchId" IS NULL
          OR rg."branchId" = "Instructor"."branchId"
        )
    )
  );
