-- ULTM8 Phase 11 — ClassesModule: booking + waitlist (Spec 55 §9/§10). See the Phase
-- 11 kickoff prompt for the full scoping rationale and every citation this migration's
-- own comments below rely on.
--
-- Additive-only (Decision 32) — no existing table/policy from any prior migration is
-- touched.
--
-- Same provenance caveat as every prior migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` (no reachable Postgres in this environment) —
-- verify with a real `prisma migrate diff`/`migrate dev` run before trusting this past
-- a walking skeleton.

CREATE TYPE "BookingStatus" AS ENUM ('UPCOMING', 'COMPLETED', 'CANCELLED', 'NO_SHOW');
CREATE TYPE "RefundResolution" AS ENUM ('REFUNDED', 'WITHHELD');
CREATE TYPE "WaitlistStatus" AS ENUM ('WAITING', 'NOTIFIED', 'CLAIMED', 'EXPIRED', 'CANCELLED');

-- ============================================================================
-- Booking — FOUND ON THE PHASE 11 KICKOFF VERIFICATION PASS, BEFORE BUILD: this is
-- the SAME class of narrow "one specific Student's own record" data Membership/
-- Transaction (Phase 9), WaiverSignature (Phase 10), and StudentRank (Phase 10b)
-- already established a narrow RLS shape for — recorded fresh here as Decision 89
-- (docs/decisions/POST-SPEC-55-DECISION-LOG.md) rather than leaning on those three as
-- settled precedent, since one of them (WaiverSignature) is itself still explicitly
-- open pending Architect confirmation, and only StudentRank's shape was ever actually
-- logged as a numbered Decision before this one.
--
-- UNLIKE those three, Booking also needs a second, genuinely new read pattern: a Class
-- roster/capacity check that must see EVERY Student's Booking for one Class, not just
-- one Student's own row — no narrow self-or-owner policy can serve that. So Booking's
-- RLS is deliberately ASYMMETRIC:
--   1. `booking_school_staff_or_self` — narrow, ALL commands: SCHOOL_OWNER_MANAGER at
--      the row's own schoolId, OR the row's own Student. Same shape/reasoning as
--      Membership/Transaction's own policy in the Phase 9 migration.
--   2. `booking_staff_read` — broad, SELECT only: any active RoleGrant holder
--      (SCHOOL_OWNER_MANAGER/BRANCH_STAFF/INSTRUCTOR) at the School, using the SAME
--      three-way School/Branch structure Class's own policy already established
--      (20260907000000_classes_module) — a School-level grant sees every Branch's
--      Bookings; a Branch-scoped grant sees its own Branch's plus School-wide ones.
-- These two are additive permissive policies (Postgres ORs them together) — the exact
-- mechanism this schema already exercises for ultm8_jobs's own read policies below,
-- just applied here to two DIFFERENT roles' access within ultm8_app itself. A Staff
-- WRITE to one specific Student's Booking (cancel-on-behalf-of, the rank-gate
-- override) still goes through TenantAuthorizationService.assertStaffAtSchool() +
-- running the write under the TARGET Student's own tenant context — the established
-- Phase 9/10b mechanism — NOT through policy 2, which is SELECT-only by design.
-- ============================================================================

CREATE TABLE "Booking" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "studentId" TEXT NOT NULL,
    "classId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "branchId" TEXT,
    "status" "BookingStatus" NOT NULL DEFAULT 'UPCOMING',
    "sourceMembershipId" TEXT NOT NULL,
    "overriddenById" TEXT,
    "overrideReason" TEXT,
    "refundResolution" "RefundResolution",
    "resolvedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Booking_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Booking_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    -- RESTRICT, not CASCADE — a Class has no delete endpoint in this codebase anyway
    -- (same "no delete method" convention as Discipline/Rank/Waiver/MembershipPlan),
    -- and cascading a hypothetical future Class deletion into deleting Students' own
    -- booking history would be destructive. Same reasoning as StudentRank.
    -- currentRankId's own ON DELETE RESTRICT (Phase 10b migration).
    CONSTRAINT "Booking_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Booking_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Booking_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE,
    -- RESTRICT — sourceMembershipId is this row's own audit trail of which Membership
    -- funded it; a Membership has no delete endpoint either, same reasoning as classId
    -- above.
    CONSTRAINT "Booking_sourceMembershipId_fkey" FOREIGN KEY ("sourceMembershipId") REFERENCES "Membership"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Booking_overriddenById_fkey" FOREIGN KEY ("overriddenById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Booking_resolvedById_fkey" FOREIGN KEY ("resolvedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON "Booking" TO ultm8_app;

-- Composite indexes leading with the tenant column (Decision 30).
CREATE INDEX "Booking_schoolId_idx" ON "Booking"("schoolId");
CREATE INDEX "Booking_schoolId_branchId_idx" ON "Booking"("schoolId", "branchId");
CREATE INDEX "Booking_studentId_idx" ON "Booking"("studentId");
CREATE INDEX "Booking_classId_idx" ON "Booking"("classId");

-- "One active Booking per Student per Class" (kickoff prompt §5) — a partial unique
-- index, not an app-layer findFirst-then-create check, same TOCTOU-avoidance technique
-- Membership's own one-active-general-access-per-school guard already established
-- (Phase 9). A Cancelled/Completed/No-Show Booking must never block a fresh re-booking
-- of the same Class, hence the WHERE clause scoping this to UPCOMING only.
CREATE UNIQUE INDEX "Booking_one_upcoming_per_student_per_class" ON "Booking"("studentId", "classId")
  WHERE "status" = 'UPCOMING';

ALTER TABLE "Booking" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Booking" FORCE ROW LEVEL SECURITY;

CREATE POLICY "booking_school_staff_or_self" ON "Booking"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "Booking"."schoolId"
        AND rg."role" = 'SCHOOL_OWNER_MANAGER'
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
    OR "Booking"."studentId" = current_setting('app.current_user_id', true)
  );

-- Same three-way School/Branch structure as class_tenant_isolation
-- (20260907000000_classes_module) — a School-level grant (branchId NULL) sees every
-- Branch's Bookings; a Branch-scoped grant sees its own Branch's Bookings plus
-- School-wide ones (Booking.branchId NULL); never another Branch's.
CREATE POLICY "booking_staff_read" ON "Booking"
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "Booking"."schoolId"
        AND rg."role" IN ('SCHOOL_OWNER_MANAGER', 'BRANCH_STAFF', 'INSTRUCTOR')
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
        AND (
          rg."branchId" IS NULL
          OR "Booking"."branchId" IS NULL
          OR rg."branchId" = "Booking"."branchId"
        )
    )
  );

-- ultm8_jobs: booking-no-show-processing reads every UPCOMING Booking whose Class has
-- passed its no-show cutoff (a global sweep, no caller/tenant context — the exact
-- situation ultm8_jobs already exists for) and flips it to NO_SHOW. No INSERT/DELETE
-- grant — the job never creates or removes a Booking, only transitions its status.
GRANT SELECT, UPDATE ON "Booking" TO ultm8_jobs;
CREATE POLICY "booking_jobs_read" ON "Booking"
  FOR SELECT
  TO ultm8_jobs
  USING (true);
CREATE POLICY "booking_jobs_update" ON "Booking"
  FOR UPDATE
  TO ultm8_jobs
  USING (true)
  WITH CHECK (true);

-- ============================================================================
-- BookingAttendee — the `whoJoinYou` attendee list (schema.prisma's own model
-- comment has the full reasoning for why this is its own explicit relation, not a
-- schema-confirmed entity name).
--
-- FOUND ON REVIEW, before this ever shipped: a single EXISTS-against-Booking policy
-- covering ALL commands does NOT safely delegate to "Booking's own two policies" the
-- way RankRequiredSkill's delegation does — RankRequiredSkill's parent (Rank) has one
-- SYMMETRIC ALL-commands policy, where read and write authority are identical, so a
-- blind EXISTS is safe there. Booking is deliberately ASYMMETRIC (a broader SELECT-
-- only Staff-read policy layered on top of a narrower ALL-commands self-or-owner
-- policy) — and a subquery is ALWAYS evaluated as a READ, regardless of which command
-- the OUTER policy is guarding. A single `EXISTS (SELECT 1 FROM "Booking" ...)` policy
-- covering INSERT/UPDATE/DELETE on BookingAttendee would therefore silently inherit
-- Booking's BROAD read visibility as write authority — letting BRANCH_STAFF/
-- INSTRUCTOR (who can SELECT any Booking at their School via booking_staff_read)
-- insert/update/delete BookingAttendee rows directly, well past what Booking's own
-- write policy permits them.
--
-- Fixed with TWO separate policies instead of one, mirroring Booking's own asymmetry
-- rather than blindly reusing RankRequiredSkill's simpler single-policy shape:
--   1. `booking_attendee_read` (SELECT only) — still a plain EXISTS-against-Booking
--      visibility check, correct here because SELECT-vs-SELECT is exactly the
--      composition Booking's own two policies already express for reads.
--   2. `booking_attendee_write` (all other commands — the default, no FOR clause) —
--      re-derives Booking's NARROW ownership predicate inline (SCHOOL_OWNER_MANAGER
--      at the parent Booking's own schoolId, or the parent Booking's own studentId)
--      rather than checking Booking's general visibility, so it cannot be widened by
--      Booking's own broad SELECT-only policy.
-- ============================================================================

CREATE TABLE "BookingAttendee" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "bookingId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "membershipId" TEXT NOT NULL,
    "refundResolution" "RefundResolution",
    "resolvedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "BookingAttendee_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "BookingAttendee_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "BookingAttendee_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    -- RESTRICT — same audit-trail reasoning as Booking.sourceMembershipId above.
    CONSTRAINT "BookingAttendee_membershipId_fkey" FOREIGN KEY ("membershipId") REFERENCES "Membership"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "BookingAttendee_resolvedById_fkey" FOREIGN KEY ("resolvedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON "BookingAttendee" TO ultm8_app;

CREATE INDEX "BookingAttendee_schoolId_idx" ON "BookingAttendee"("schoolId");
CREATE INDEX "BookingAttendee_bookingId_idx" ON "BookingAttendee"("bookingId");
CREATE INDEX "BookingAttendee_membershipId_idx" ON "BookingAttendee"("membershipId");

ALTER TABLE "BookingAttendee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BookingAttendee" FORCE ROW LEVEL SECURITY;

-- SELECT: a plain visibility delegation is correct here — SELECT-vs-SELECT is
-- exactly the composition Booking's own two (narrow + broad) policies already
-- express for reads, so anyone who can see the parent Booking can see its
-- attendees.
CREATE POLICY "booking_attendee_read" ON "BookingAttendee"
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM "Booking" b WHERE b."id" = "BookingAttendee"."bookingId"
    )
  );

-- INSERT/UPDATE/DELETE (the default — no FOR clause): re-derives Booking's NARROW
-- ownership predicate directly (not a generic "is the Booking visible" check) so a
-- BRANCH_STAFF/INSTRUCTOR caller — who CAN see the parent Booking via the broad
-- read policy above — still cannot write a BookingAttendee row directly; only the
-- SAME SCHOOL_OWNER_MANAGER-or-owning-Student condition Booking's own write policy
-- enforces applies here too.
CREATE POLICY "booking_attendee_write" ON "BookingAttendee"
  USING (
    EXISTS (
      SELECT 1 FROM "Booking" b
      WHERE b."id" = "BookingAttendee"."bookingId"
        AND (
          EXISTS (
            SELECT 1 FROM "RoleGrant" rg
            WHERE rg."schoolId" = b."schoolId"
              AND rg."role" = 'SCHOOL_OWNER_MANAGER'
              AND rg."userId" = current_setting('app.current_user_id', true)
              AND rg."revokedAt" IS NULL
          )
          OR b."studentId" = current_setting('app.current_user_id', true)
        )
    )
  );

-- FOUND ON REVIEW, before this ever shipped: no background job touches guest rows
-- (booking-no-show-processing only flips Booking.status; the waitlist cascade never
-- creates BookingAttendee rows), but the CAPACITY CHECK itself does need this —
-- BookingsService/WaitlistService's occupancy count runs via PrismaJobsService
-- (ultm8_jobs), NOT the caller's own tenant context, precisely because Booking/
-- BookingAttendee's own narrow-plus-broad-Staff-only-read RLS (Decision 89) means an
-- ORDINARY STUDENT caller can never see another Student's rows to count them at all
-- — the broad read policy only admits Staff roles. Without ultm8_jobs bypassing RLS
-- for this one read, a capacity check from a Student's own booking attempt would
-- always undercount (seeing only their own rows), silently defeating the whole
-- Full-Class gate. See BookingsService.countOccupiedSeats's own comment.
GRANT SELECT ON "BookingAttendee" TO ultm8_jobs;
CREATE POLICY "booking_attendee_jobs_read" ON "BookingAttendee"
  FOR SELECT
  TO ultm8_jobs
  USING (true);

-- ============================================================================
-- WaitlistEntry — same asymmetric narrow-plus-broad RLS structure as Booking above,
-- same Decision 89, for the same reasoning (schema.prisma's own model comment has the
-- full text).
-- ============================================================================

CREATE TABLE "WaitlistEntry" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "studentId" TEXT NOT NULL,
    "classId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "branchId" TEXT,
    "position" INTEGER NOT NULL,
    "status" "WaitlistStatus" NOT NULL DEFAULT 'WAITING',
    "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "notifiedAt" TIMESTAMP(3),
    "claimByDeadline" TIMESTAMP(3),
    "claimedBookingId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "WaitlistEntry_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "WaitlistEntry_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    -- RESTRICT — same reasoning as Booking.classId above.
    CONSTRAINT "WaitlistEntry_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "WaitlistEntry_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "WaitlistEntry_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE,
    -- SET NULL, not RESTRICT/CASCADE — Booking has no delete endpoint in this codebase
    -- (see Booking.classId's own comment above for the general convention), so this is
    -- a defensive default rather than a reachable path today; preserves the
    -- WaitlistEntry's own history (position/timestamps) rather than deleting it if a
    -- claimed Booking were ever removed some other way.
    CONSTRAINT "WaitlistEntry_claimedBookingId_fkey" FOREIGN KEY ("claimedBookingId") REFERENCES "Booking"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "WaitlistEntry_claimedBookingId_key" ON "WaitlistEntry"("claimedBookingId");

GRANT SELECT, INSERT, UPDATE, DELETE ON "WaitlistEntry" TO ultm8_app;

CREATE INDEX "WaitlistEntry_schoolId_idx" ON "WaitlistEntry"("schoolId");
CREATE INDEX "WaitlistEntry_classId_position_idx" ON "WaitlistEntry"("classId", "position");
CREATE INDEX "WaitlistEntry_studentId_idx" ON "WaitlistEntry"("studentId");

-- "One active (Waiting/Notified) WaitlistEntry per Student per Class" — same partial-
-- unique-index technique as Booking's own guard above. A Claimed/Expired/Cancelled
-- entry must never block rejoining the same Class's waitlist.
CREATE UNIQUE INDEX "WaitlistEntry_one_active_per_student_per_class" ON "WaitlistEntry"("studentId", "classId")
  WHERE "status" IN ('WAITING', 'NOTIFIED');

ALTER TABLE "WaitlistEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WaitlistEntry" FORCE ROW LEVEL SECURITY;

CREATE POLICY "waitlist_entry_school_staff_or_self" ON "WaitlistEntry"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "WaitlistEntry"."schoolId"
        AND rg."role" = 'SCHOOL_OWNER_MANAGER'
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
    OR "WaitlistEntry"."studentId" = current_setting('app.current_user_id', true)
  );

CREATE POLICY "waitlist_entry_staff_read" ON "WaitlistEntry"
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "WaitlistEntry"."schoolId"
        AND rg."role" IN ('SCHOOL_OWNER_MANAGER', 'BRANCH_STAFF', 'INSTRUCTOR')
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
        AND (
          rg."branchId" IS NULL
          OR "WaitlistEntry"."branchId" IS NULL
          OR rg."branchId" = "WaitlistEntry"."branchId"
        )
    )
  );

-- FOUND ON REVIEW, before this ever shipped: notifyNextWaitingEntry() (the shared
-- helper both the seat-freed and sweep-expired job paths call) reads through Class
-- into School.waitlistClaimWindowMinutes to compute claimByDeadline — but no prior
-- migration in this repo ever granted ultm8_jobs SELECT on "School" (it wasn't
-- needed until now). Without this, every single notify attempt throws Postgres
-- 42501 ("permission denied for table School"), silently killing the entire
-- waitlist-cascade feature — same additive-policy pattern already established for
-- Branch/TimetableSlot (20260908000000_timetable_module).
GRANT SELECT ON "School" TO ultm8_jobs;
CREATE POLICY "school_jobs_read" ON "School"
  FOR SELECT
  TO ultm8_jobs
  USING (true);

-- ultm8_jobs: waitlist-cascade-processing reads every Class's Waiting/Notified
-- entries in position order (a freed-seat sweep, no caller/tenant context) and flips
-- status (Waiting -> Notified on a freed seat; Notified -> Expired past
-- claimByDeadline). No INSERT/DELETE grant — the job never creates or removes a
-- WaitlistEntry, only transitions status/notifiedAt/claimByDeadline; joining (INSERT)
-- and withdrawing (DELETE, or a status-only UPDATE) stay caller-initiated, under
-- ultm8_app, unaffected by this grant.
GRANT SELECT, UPDATE ON "WaitlistEntry" TO ultm8_jobs;
CREATE POLICY "waitlist_entry_jobs_read" ON "WaitlistEntry"
  FOR SELECT
  TO ultm8_jobs
  USING (true);
CREATE POLICY "waitlist_entry_jobs_update" ON "WaitlistEntry"
  FOR UPDATE
  TO ultm8_jobs
  USING (true)
  WITH CHECK (true);
