-- ULTM8 Phase 7 — SettingsModule (GET /settings/languages, GET /settings/currencies,
-- GET /legal/{doc} only; see the Phase 7 kickoff prompt for the full scoping
-- rationale — the roadmap's original Phase 7 pick, SubscriptionPlansModule, and its
-- sibling TranslationsModule are both deferred instead: their authoring surfaces are
-- "Platform Admin app only" per Spec 55, and Platform Admin's own confirmed
-- requirement is a wholly separate SSO+2FA identity realm (§4.4) that doesn't exist
-- anywhere in this codebase yet).
--
-- Additive-only (Decision 32) — no existing table/policy from any prior migration is
-- touched.
--
-- Same provenance caveat as every prior migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` (no reachable Postgres in this environment) —
-- verify with a real `prisma migrate diff`/`migrate dev` run before trusting this
-- past a walking skeleton.
--
-- `languages`/`currencies` are NOT tables — see schema.prisma's own comment on why
-- (no confirmed admin-editable list exists yet; they're served as plain TypeScript
-- constants from SettingsService instead). This migration only covers LegalDocument.

CREATE TABLE "LegalDocument" (
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "LegalDocument_pkey" PRIMARY KEY ("slug")
);

-- Baseline table privileges for ultm8_app — the role apps/api actually connects as
-- for every query (see PrismaAppService's header comment). Without this, the query
-- fails with Postgres 42501 ("permission denied for table LegalDocument") before
-- anything else is even evaluated — the exact omission that cost Phase 4 a
-- first-real-Postgres-run CI failure (commit 2636873) on Class; Phase 5's
-- TimetableSlot and Phase 6's Instructor migrations both already got this right on
-- the first attempt, so this is the third migration in a row not to repeat it.
GRANT SELECT, INSERT, UPDATE, DELETE ON "LegalDocument" TO ultm8_app;

-- Deliberately NO "ALTER TABLE ... ENABLE ROW LEVEL SECURITY" here — this table has
-- no tenant column to key a policy on, unlike every RLS-protected table this project
-- has added so far. Not an oversight: this follows the exact precedent
-- 20260902000000_init already set for AdminUser, the one other table in this schema
-- with no tenant column, which is CREATE TABLE'd there but never gets RLS enabled
-- either. Global, platform-level content (the same category as AdminUser's own
-- identity rows) genuinely has no per-caller row subset to restrict.

-- Seed the two confirmed `{doc}` slugs Spec 55's own screen inventory names as
-- genuinely legal instruments ("Static / legal — Help & Support, Terms and
-- Conditions, Privacy Statement — Content screens, no CMS fields beyond static text
-- observed") — content left NULL deliberately. The actual legal text was never
-- captured anywhere in the spec or designs, and inventing placeholder legal copy
-- pretending to be real would be worse than leaving this honestly empty pending
-- actual legal/product input. "Help & Support" is listed on the same
-- design-inventory line but reads as support/FAQ content, a different concept — not
-- seeded here, flagged rather than silently folded in (see the Phase 7 kickoff
-- prompt for the full reasoning). This is the first migration in this repo to seed
-- data via INSERT (checked — no prior migration does; not following an established
-- pattern, a new one, flagged as such) — justified here because these two rows are
-- structural/reference data, closer to the role `Role`/`Weekday` enum values already
-- play in this schema than to a row a School or user would ever create.
INSERT INTO "LegalDocument" ("slug", "title", "content", "updatedAt") VALUES
    ('terms-and-conditions', 'Terms and Conditions', NULL, CURRENT_TIMESTAMP),
    ('privacy-statement', 'Privacy Statement', NULL, CURRENT_TIMESTAMP);
