-- ULTM8 Phase 44 — CurriculumModule (Lesson + LessonSkill only; see Lesson's own
-- schema.prisma comment for the full scoping rationale, the Decision 58/§7 spec
-- contradiction this resolves, and what's deliberately NOT modeled — Category,
-- Live-Lesson real-time captioning mechanics, audio description).
--
-- Same provenance caveat as every prior migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` (no reachable Postgres in this environment) —
-- verify with a real `prisma migrate diff`/`migrate dev` run, AND the cross-tenant
-- isolation CI suite, before trusting this past a walking skeleton. RLS policies in
-- this codebase have shipped wrong twice before on the first attempt (see
-- ultm8-tenant-isolation §2's own account of the RoleGrant self-referential-EXISTS
-- recursion and the School NOT EXISTS blind spot) — do not treat this file as
-- correct-by-construction just because it mirrors an existing pattern.
--
-- Additive-only (Decision 32) — no existing table/policy is touched.

CREATE TYPE "LessonFormat" AS ENUM ('PRERECORDED', 'LIVE');
CREATE TYPE "CaptionStatus" AS ENUM ('PENDING', 'PROCESSING', 'READY', 'FAILED');

-- ============================================================================
-- Lesson — School-scoped catalog/content data, not a per-Student record. RLS shape
-- modeled directly on Class's own "class_tenant_isolation" policy
-- (20260907000000_classes_module): a single combined USING policy admitting ANY
-- active RoleGrant holder at the School (Student included — Decision 58's own
-- text has Lessons "surfacing automatically wherever [a] skill already appears...
-- a student's profile"), same "School/Branch RLS admits any role, business-layer
-- narrows writes" split already established for Discipline/Rank/Skill above. No
-- branchId — Decision 58 never scopes Lesson to a Branch, unlike Class/TimetableSlot/
-- Instructor/Booking's confirmed four-entity Branch-RLS list (ultm8-tenant-isolation
-- §2). Actual write authorization (Staff/Instructor only, via
-- TenantAuthorizationService.assertStaffAtSchool) is enforced in CurriculumService,
-- not here — same division of responsibility as every other RLS-scoped table in
-- this schema.
-- ============================================================================

CREATE TABLE "Lesson" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "schoolId" TEXT NOT NULL,
    "instructorId" TEXT,
    "title" TEXT NOT NULL,
    "category" TEXT,
    "durationSeconds" INTEGER,
    "description" TEXT,
    "format" "LessonFormat" NOT NULL,
    "videoRef" TEXT,
    "captionStatus" "CaptionStatus" NOT NULL DEFAULT 'PENDING',
    "captionTrackRef" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Lesson_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Lesson_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Lesson_instructorId_fkey" FOREIGN KEY ("instructorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- Baseline table privileges for ultm8_app — see Class's own identical grant
-- comment (20260907000000_classes_module) for why this line is not optional:
-- without it, RLS policies below are unreachable, Postgres rejects with 42501
-- ("permission denied for table Lesson") before RLS is even evaluated.
GRANT SELECT, INSERT, UPDATE, DELETE ON "Lesson" TO ultm8_app;

-- Composite index leading with the tenant column (Decision 30).
CREATE INDEX "Lesson_schoolId_idx" ON "Lesson"("schoolId");
CREATE INDEX "Lesson_instructorId_idx" ON "Lesson"("instructorId");

ALTER TABLE "Lesson" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Lesson" FORCE ROW LEVEL SECURITY;
CREATE POLICY "lesson_tenant_isolation" ON "Lesson"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "Lesson"."schoolId"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
  );

-- ============================================================================
-- LessonSkill — explicit join table for Lesson's confirmed many-to-many "linked
-- skill(s)" (Spec 55 §6.1). No schoolId of its own — RLS delegates entirely to
-- Lesson/Skill's own policies via the FK-existence join below, same reasoning and
-- same shape as RankRequiredSkill's own policy (20260914000000_ranks_module): this
-- table carries no queryable data beyond the two FKs, so a caller can only ever
-- reach a row here by already having Lesson/Skill visibility through their own
-- policies.
-- ============================================================================

CREATE TABLE "LessonSkill" (
    "lessonId" TEXT NOT NULL,
    "skillId" TEXT NOT NULL,
    CONSTRAINT "LessonSkill_pkey" PRIMARY KEY ("lessonId", "skillId"),
    CONSTRAINT "LessonSkill_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lesson"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "LessonSkill_skillId_fkey" FOREIGN KEY ("skillId") REFERENCES "Skill"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "LessonSkill_skillId_idx" ON "LessonSkill"("skillId");
GRANT SELECT, INSERT, UPDATE, DELETE ON "LessonSkill" TO ultm8_app;

ALTER TABLE "LessonSkill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LessonSkill" FORCE ROW LEVEL SECURITY;
CREATE POLICY "lesson_skill_tenant_isolation" ON "LessonSkill"
  USING (
    EXISTS (SELECT 1 FROM "Lesson" l WHERE l."id" = "LessonSkill"."lessonId")
    AND EXISTS (SELECT 1 FROM "Skill" s WHERE s."id" = "LessonSkill"."skillId")
  );
