-- Decision 111, Phase A — Stripe dispute handling (Decision 55) built end to end.
-- Adds the one new column this phase's design actually needs:
-- `stripePaymentIntentId` on FranchiseFeeCharge/PlatformCharge, the correlator a
-- `charge.dispute.*` webhook (payment_intent-keyed only — see Dispute's own type
-- definition, verified against the installed Stripe SDK) needs to find its row.
-- Transaction already has this column (Phase 9) — nothing to add there.
--
-- Originally scoped as "no migration needed" before implementation — corrected once
-- direct verification against the installed Stripe SDK's own type definitions
-- (node_modules/stripe/cjs/resources/{Charges,PaymentIntents}.d.ts) showed this API
-- version carries no `invoice` field on Charge/PaymentIntent at all, so the classic
-- reverse-correlation path (PaymentIntent/Charge -> Invoice) this plan's earlier
-- draft assumed does not exist. The only reachable path is forward, from Invoice's
-- own `payments` list (InvoicePayment.payment.payment_intent) at
-- handleInvoicePaid() time — see stripe-webhook-processing.processor.ts's own
-- updated comment.
--
-- Additive-only (Decision 32) — no existing table/policy rewritten. No new GRANT
-- statements needed: both tables already carry a whole-table (not column-scoped)
-- `GRANT SELECT, INSERT, UPDATE ... TO ultm8_jobs` (20260922000000_franchise_fee_
-- charge_module, 20261005000000_subscription_plans_module) that already covers any
-- new column added to either table.
--
-- Same provenance caveat as every prior migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` (no reachable Postgres in this environment at
-- authoring time) — verify with a real Postgres run before trusting this past a
-- walking skeleton.

ALTER TABLE "FranchiseFeeCharge" ADD COLUMN "stripePaymentIntentId" TEXT;
CREATE UNIQUE INDEX "FranchiseFeeCharge_stripePaymentIntentId_key" ON "FranchiseFeeCharge"("stripePaymentIntentId");

ALTER TABLE "PlatformCharge" ADD COLUMN "stripePaymentIntentId" TEXT;
CREATE UNIQUE INDEX "PlatformCharge_stripePaymentIntentId_key" ON "PlatformCharge"("stripePaymentIntentId");
