-- ULTM8 Phase 10b — RanksModule (belt/grading reference data + single-Student
-- promotion/downgrade/stripe-award/skill-sign-off actions). See the Phase 10b
-- kickoff prompt for the full scoping rationale — bulk-promote/bulk-stripe-award
-- endpoints, the readiness-bucket/progress-% computation (Decision 75, genuinely
-- undesigned), and Booking-time rank-gating enforcement (Booking doesn't exist
-- yet) are all deliberately deferred, not silently built around.
--
-- Additive-only (Decision 32) — no existing table/policy from any prior migration
-- is touched.
--
-- Same provenance caveat as every prior migration in this repo: hand-authored, not
-- generated by `prisma migrate dev` (no reachable Postgres in this environment) —
-- verify with a real `prisma migrate diff`/`migrate dev` run before trusting this
-- past a walking skeleton.

CREATE TYPE "PromotionEventType" AS ENUM ('PROMOTION', 'DOWNGRADE', 'STRIPE_AWARD', 'BULK_PROMOTION', 'BULK_STRIPE_AWARD');
CREATE TYPE "SkillSignOffStatus" AS ENUM ('NOT_STARTED', 'LEARNING', 'SIGNED_OFF');

-- ============================================================================
-- Discipline, Rank, RankStripeTier, Skill, RankRequiredSkill — a School's belt/
-- grading catalog. Public-visibility catalog data, not a per-Student record — RLS
-- shape matches Class/TimetableSlot/MembershipPlan/Waiver's own "any active
-- RoleGrant holder at the School" pattern, NOT StudentRank's narrower shape below
-- (see that table's own header comment for why those need a materially different
-- policy — same split Phase 9/10 already established between catalog tables and
-- per-Student records).
--
-- Rank, RankStripeTier, and Skill each carry their OWN denormalized schoolId
-- (not just disciplineId) — without it, Rank's RLS policy would need a join
-- through Discipline to reach RoleGrant, and RankStripeTier (Rank's own child)
-- would need two joins. Decision 30's "composite index leading with the tenant
-- column" principle assumes a direct tenant column on every RLS-scoped table.
-- ============================================================================

CREATE TABLE "Discipline" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "schoolId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "classTypesOffered" TEXT[] NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Discipline_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Discipline_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON "Discipline" TO ultm8_app;
CREATE INDEX "Discipline_schoolId_idx" ON "Discipline"("schoolId");

ALTER TABLE "Discipline" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Discipline" FORCE ROW LEVEL SECURITY;
CREATE POLICY "discipline_tenant_isolation" ON "Discipline"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "Discipline"."schoolId"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
  );

CREATE TABLE "Rank" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "disciplineId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "order" INTEGER NOT NULL,
    "primaryColour" TEXT NOT NULL,
    "secondaryColour" TEXT,
    "weeklyClassCountCap" INTEGER,
    "yearsInRankFlag" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Rank_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Rank_disciplineId_fkey" FOREIGN KEY ("disciplineId") REFERENCES "Discipline"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Rank_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "Rank_disciplineId_order_key" ON "Rank"("disciplineId", "order");
GRANT SELECT, INSERT, UPDATE, DELETE ON "Rank" TO ultm8_app;
CREATE INDEX "Rank_schoolId_idx" ON "Rank"("schoolId");
CREATE INDEX "Rank_disciplineId_idx" ON "Rank"("disciplineId");

ALTER TABLE "Rank" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Rank" FORCE ROW LEVEL SECURITY;
CREATE POLICY "rank_tenant_isolation" ON "Rank"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "Rank"."schoolId"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
  );

CREATE TABLE "RankStripeTier" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "rankId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "order" INTEGER NOT NULL,
    "count" INTEGER NOT NULL,
    "colour" TEXT NOT NULL,
    "classesRequired" INTEGER,
    "minimumDaysInRank" INTEGER,
    "eligibleClassTypes" TEXT[] NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "RankStripeTier_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "RankStripeTier_rankId_fkey" FOREIGN KEY ("rankId") REFERENCES "Rank"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "RankStripeTier_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "RankStripeTier_rankId_order_key" ON "RankStripeTier"("rankId", "order");
GRANT SELECT, INSERT, UPDATE, DELETE ON "RankStripeTier" TO ultm8_app;
CREATE INDEX "RankStripeTier_schoolId_idx" ON "RankStripeTier"("schoolId");
CREATE INDEX "RankStripeTier_rankId_idx" ON "RankStripeTier"("rankId");

ALTER TABLE "RankStripeTier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RankStripeTier" FORCE ROW LEVEL SECURITY;
CREATE POLICY "rank_stripe_tier_tenant_isolation" ON "RankStripeTier"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "RankStripeTier"."schoolId"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
  );

CREATE TABLE "Skill" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "disciplineId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Skill_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Skill_disciplineId_fkey" FOREIGN KEY ("disciplineId") REFERENCES "Discipline"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Skill_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON "Skill" TO ultm8_app;
CREATE INDEX "Skill_schoolId_idx" ON "Skill"("schoolId");
CREATE INDEX "Skill_disciplineId_idx" ON "Skill"("disciplineId");

ALTER TABLE "Skill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Skill" FORCE ROW LEVEL SECURITY;
CREATE POLICY "skill_tenant_isolation" ON "Skill"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "Skill"."schoolId"
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
  );

-- Explicit join table (not Prisma's implicit many-to-many — see schema.prisma's
-- own comment on RankRequiredSkill for why). No schoolId of its own — RLS
-- delegates entirely to Rank/Skill's own policies via the FK join below, which is
-- safe here (unlike the earlier "avoid a join" reasoning above) because this
-- table carries no queryable data of its own beyond the two FKs themselves; a
-- caller can only ever reach a row here by already having Rank/Skill visibility.
CREATE TABLE "RankRequiredSkill" (
    "rankId" TEXT NOT NULL,
    "skillId" TEXT NOT NULL,
    CONSTRAINT "RankRequiredSkill_pkey" PRIMARY KEY ("rankId", "skillId"),
    CONSTRAINT "RankRequiredSkill_rankId_fkey" FOREIGN KEY ("rankId") REFERENCES "Rank"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "RankRequiredSkill_skillId_fkey" FOREIGN KEY ("skillId") REFERENCES "Skill"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "RankRequiredSkill_skillId_idx" ON "RankRequiredSkill"("skillId");
GRANT SELECT, INSERT, UPDATE, DELETE ON "RankRequiredSkill" TO ultm8_app;

ALTER TABLE "RankRequiredSkill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RankRequiredSkill" FORCE ROW LEVEL SECURITY;
CREATE POLICY "rank_required_skill_tenant_isolation" ON "RankRequiredSkill"
  USING (
    EXISTS (SELECT 1 FROM "Rank" r WHERE r."id" = "RankRequiredSkill"."rankId")
    AND EXISTS (SELECT 1 FROM "Skill" s WHERE s."id" = "RankRequiredSkill"."skillId")
  );

-- ============================================================================
-- StudentRank, StudentRankSkillStatus, PromotionEvent — FOUND ON THE PHASE 10b
-- VERIFICATION PASS, RESOLVED AS A DIRECT PRODUCT DECISION, RECORDED AS DECISION
-- 88 (docs/decisions/POST-SPEC-55-DECISION-LOG.md) — NOT LEFT TO GUESS: these
-- three carry one specific Student's own grading data (classesAttendedToward-
-- Checkpoint, per-skill sign-off status, rank-history) — the same class of "not
-- School-wide catalog data" concern Phase 9 already found for Membership/
-- Transaction (verified against this repo's own merged migration), and Phase
-- 10's WaiversModule (PR #7) applies the same way for WaiverSignature. Same
-- narrow shape: SCHOOL_OWNER_MANAGER RoleGrant
-- holder at the row's own schoolId gets full read/write; the row's own Student
-- (studentId = current_setting('app.current_user_id')) gets read/write of their
-- OWN rows only; no other role (BRANCH_STAFF, INSTRUCTOR included) gets any row
-- access at all.
--
-- Instructor/Staff functional access (checking a Student's rank for class
-- eligibility, the Grading Board) is NOT traded away for this — it's handled at
-- the APPLICATION layer exactly the way Phase 9 already built for GET
-- /students/{id}/membership-status: TenantAuthorizationService.assertStaffAtSchool()
-- authorizes the caller, then the underlying read runs under the TARGET
-- Student's own tenant context (which satisfies the self-only clause below), not
-- the caller's — never by broadening this policy to admit Instructor/Branch
-- Staff directly.
-- ============================================================================

-- currentRankId is ON DELETE RESTRICT, not this schema's usual CASCADE for a
-- required FK (e.g. Membership -> MembershipPlan) — deliberate: cascading a Rank
-- deletion into deleting every Student's own StudentRank row that currently
-- points to it would destroy real grading history as a side effect of a catalog
-- edit. No Rank-delete endpoint exists this phase anyway (matching the
-- established "general tenant offboarding is [UNRESOLVED]" pattern), so this is
-- moot in practice today — kept as the correct choice on principle regardless.
CREATE TABLE "StudentRank" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "studentId" TEXT NOT NULL,
    "disciplineId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "currentRankId" TEXT NOT NULL,
    "currentStripeId" TEXT,
    "dateOfCurrentRank" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "classesAttendedTowardCheckpoint" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "StudentRank_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "StudentRank_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "StudentRank_disciplineId_fkey" FOREIGN KEY ("disciplineId") REFERENCES "Discipline"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "StudentRank_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "StudentRank_currentRankId_fkey" FOREIGN KEY ("currentRankId") REFERENCES "Rank"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "StudentRank_currentStripeId_fkey" FOREIGN KEY ("currentStripeId") REFERENCES "RankStripeTier"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "StudentRank_studentId_disciplineId_key" ON "StudentRank"("studentId", "disciplineId");
GRANT SELECT, INSERT, UPDATE, DELETE ON "StudentRank" TO ultm8_app;
CREATE INDEX "StudentRank_schoolId_idx" ON "StudentRank"("schoolId");
CREATE INDEX "StudentRank_studentId_idx" ON "StudentRank"("studentId");
CREATE INDEX "StudentRank_disciplineId_idx" ON "StudentRank"("disciplineId");

ALTER TABLE "StudentRank" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StudentRank" FORCE ROW LEVEL SECURITY;
CREATE POLICY "student_rank_school_staff_or_self" ON "StudentRank"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "StudentRank"."schoolId"
        AND rg."role" = 'SCHOOL_OWNER_MANAGER'
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
    OR "StudentRank"."studentId" = current_setting('app.current_user_id', true)
  );

CREATE TABLE "StudentRankSkillStatus" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "studentRankId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "skillId" TEXT NOT NULL,
    "status" "SkillSignOffStatus" NOT NULL DEFAULT 'NOT_STARTED',
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "StudentRankSkillStatus_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "StudentRankSkillStatus_studentRankId_fkey" FOREIGN KEY ("studentRankId") REFERENCES "StudentRank"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "StudentRankSkillStatus_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "StudentRankSkillStatus_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "StudentRankSkillStatus_skillId_fkey" FOREIGN KEY ("skillId") REFERENCES "Skill"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "StudentRankSkillStatus_studentRankId_skillId_key" ON "StudentRankSkillStatus"("studentRankId", "skillId");
GRANT SELECT, INSERT, UPDATE, DELETE ON "StudentRankSkillStatus" TO ultm8_app;
CREATE INDEX "StudentRankSkillStatus_schoolId_idx" ON "StudentRankSkillStatus"("schoolId");
CREATE INDEX "StudentRankSkillStatus_studentId_idx" ON "StudentRankSkillStatus"("studentId");
CREATE INDEX "StudentRankSkillStatus_studentRankId_idx" ON "StudentRankSkillStatus"("studentRankId");

ALTER TABLE "StudentRankSkillStatus" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StudentRankSkillStatus" FORCE ROW LEVEL SECURITY;
CREATE POLICY "student_rank_skill_status_school_staff_or_self" ON "StudentRankSkillStatus"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "StudentRankSkillStatus"."schoolId"
        AND rg."role" = 'SCHOOL_OWNER_MANAGER'
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
    OR "StudentRankSkillStatus"."studentId" = current_setting('app.current_user_id', true)
  );

CREATE TABLE "PromotionEvent" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "studentRankId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "type" "PromotionEventType" NOT NULL,
    "performedById" TEXT NOT NULL,
    "fromRankId" TEXT,
    "toRankId" TEXT,
    "fromStripeTierId" TEXT,
    "toStripeTierId" TEXT,
    "acknowledgedWithoutSkillSignoff" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PromotionEvent_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "PromotionEvent_studentRankId_fkey" FOREIGN KEY ("studentRankId") REFERENCES "StudentRank"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PromotionEvent_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PromotionEvent_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PromotionEvent_performedById_fkey" FOREIGN KEY ("performedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PromotionEvent_fromRankId_fkey" FOREIGN KEY ("fromRankId") REFERENCES "Rank"("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "PromotionEvent_toRankId_fkey" FOREIGN KEY ("toRankId") REFERENCES "Rank"("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "PromotionEvent_fromStripeTierId_fkey" FOREIGN KEY ("fromStripeTierId") REFERENCES "RankStripeTier"("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "PromotionEvent_toStripeTierId_fkey" FOREIGN KEY ("toStripeTierId") REFERENCES "RankStripeTier"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON "PromotionEvent" TO ultm8_app;
CREATE INDEX "PromotionEvent_schoolId_idx" ON "PromotionEvent"("schoolId");
CREATE INDEX "PromotionEvent_studentId_idx" ON "PromotionEvent"("studentId");
CREATE INDEX "PromotionEvent_studentRankId_idx" ON "PromotionEvent"("studentRankId");

ALTER TABLE "PromotionEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PromotionEvent" FORCE ROW LEVEL SECURITY;
CREATE POLICY "promotion_event_school_staff_or_self" ON "PromotionEvent"
  USING (
    EXISTS (
      SELECT 1 FROM "RoleGrant" rg
      WHERE rg."schoolId" = "PromotionEvent"."schoolId"
        AND rg."role" = 'SCHOOL_OWNER_MANAGER'
        AND rg."userId" = current_setting('app.current_user_id', true)
        AND rg."revokedAt" IS NULL
    )
    OR "PromotionEvent"."studentId" = current_setting('app.current_user_id', true)
  );
